import type { Section } from "@/lib/types";
const sec: Section = {
  id: "culture-factory",
  num: 7,
  kicker: { en: "Factory 07 · Culture", zh: "工厂 07 · 文化" },
  title: { en: "The Culture Factory", zh: "文化工厂" },
  lead: { en: "Before you could read a word, culture had already written most of your operating system — your sense of shame and pride, your threshold for pain, your deepest assumptions about whether the world is fair.", zh: "在你能读懂任何文字之前，文化已经写好了你的大半个操作系统——你对羞耻与荣耀的感知，你对痛苦的忍耐阈值，以及你对世界是否公平的最深层预设。" },
  body: [
    { en: "Culture is the invisible instruction set that every society passes to its children before those children are old enough to question it. Anthropologists define it as the shared patterns of meaning — beliefs, values, rituals, language, art, food — through which a group interprets reality. Unlike genes, culture is not fixed in your cells, but it is absorbed so early and so completely that it feels, from the inside, like nature rather than nurture.", zh: "文化是每个社会在孩子尚无能力质疑之前传递给他们的隐形指令集。人类学家将其定义为一个群体赖以解读现实的共同意义模式——信仰、价值观、仪式、语言、艺术、饮食。与基因不同，文化并不固化在你的细胞里，但它被吸收得如此之早、如此彻底，以至于从内部感受起来更像天性而非教养。" },
    { en: "Geert Hofstede's decades-long research across 76 countries mapped culture onto measurable dimensions: how much a society tolerates uncertainty, whether it prizes individual achievement or group loyalty, how power distance between superiors and subordinates is accepted, and whether it leans toward short-term gratification or long-term investment. These dimensions predict, with remarkable accuracy, patterns in education, negotiation, parenting, and even architecture. A child raised in a high-uncertainty-avoidance society internalizes rule-following as safety; one raised where ambiguity is unremarkable learns to improvise.", zh: "吉尔特·霍夫斯泰德历时数十年、横跨76个国家的研究，将文化映射为可测量的维度：一个社会对不确定性的容忍程度、对个人成就还是集体忠诚的推崇、上下级之间权力距离的接受度，以及倾向于短期享乐还是长期投资。这些维度能以惊人的准确性预测教育、谈判、育儿乃至建筑风格的模式。在高不确定性规避文化中长大的孩子，将遵守规则内化为安全感；而在歧义被视为寻常的环境中成长的孩子，则学会了即兴应变。" },
    { en: "Religion is culture's most powerful amplifier. Roughly 84 percent of the global population identifies with a religious tradition, and the moral architectures those traditions provide — concepts of sin, karma, divine justice, filial piety — shape behavior in ways that persist long after formal belief fades. Max Weber famously argued that the Protestant ethic's emphasis on individual calling and worldly asceticism helped ignite Northern European capitalism. Subsequent research both supports and complicates this thesis, but the broader point holds: the theological air a child breathes leaves a chemical trace in their adult decision-making.", zh: "宗教是文化最强大的放大器。全球约84%的人口认同某种宗教传统，这些传统提供的道德框架——罪孽、因果、神圣正义、孝道等观念——以一种在正式信仰消退之后仍长期持续的方式塑造着人的行为。马克斯·韦伯曾著名地论证，新教伦理对个人天职与世俗禁欲的强调，有助于点燃北欧资本主义的引擎。后续研究对此既有支持也有质疑，但更宏观的论点仍然成立：孩子所呼吸的神学空气，在其成年后的决策中留下了化学痕迹。" },
    { en: "The individualism–collectivism axis may be the single dimension with the greatest everyday consequence. Psychologist Hazel Markus and Shinobu Kitayama showed that the self-concept differs fundamentally across cultures: Western, educated, industrialized, rich, democratic (WEIRD) samples typically describe themselves with internal traits ('I am curious, ambitious'); East Asian samples more often describe themselves relationally ('I am my mother's eldest son, a member of this team'). These are not mere vocabulary preferences — they predict how people respond to failure, how they seek help, and what they consider a good life.", zh: "个人主义与集体主义的轴线，或许是日常生活中影响最深远的单一维度。心理学家黑兹尔·马库斯与北山忍证明，自我概念在不同文化中存在根本性差异：西方、受过教育、工业化、富裕、民主（WEIRD）样本通常以内在特质描述自己（「我很好奇、有抱负」）；东亚样本则更常以关系性方式描述自己（「我是母亲的长子，是这个团队的成员」）。这不仅仅是词汇偏好的差异——它预测着人们如何应对失败、如何寻求帮助，以及他们认为什么样的生活才是美好的。" },
    { en: "Culture is not a prison — it is more like a river current. Individuals swim within it, sometimes with it, sometimes against it, occasionally redirecting it. Globalization, migration, and digital media are creating hybrid cultural identities at an unprecedented pace. Yet researchers consistently find that core value orientations instilled in childhood are remarkably stable across a lifetime, even among immigrants who adopt a new language and surface lifestyle within years. The culture factory runs early and deep; its products travel far.", zh: "文化并非监狱——它更像一条河流的水势。个体在其中游泳，有时顺流，有时逆流，偶尔也能改变它的方向。全球化、移民潮与数字媒体正以前所未有的速度塑造出混合文化身份。然而研究者持续发现，童年时期灌输的核心价值取向在整个生命历程中保持着惊人的稳定性，即便是那些数年内便习得新语言和表层生活方式的移民群体亦不例外。文化工厂运转得早而深；它的产品走得很远。" }
  ],
  cards: [
    { icon: "🏛️", title: { en: "Traditions & Ritual", zh: "传统与仪式" }, body: { en: "Recurring ceremonies — harvests, funerals, weddings, coming-of-age rites — encode a group's deepest values into the body through repetition. A child who attends 20 Lunar New Year dinners has absorbed a lesson about family obligation that no textbook can replicate.", zh: "反复举行的仪式——丰收节、葬礼、婚礼、成年礼——通过重复将一个群体最深层的价值观编码进身体。一个参加了20次春节年夜饭的孩子，已经吸收了一堂关于家庭责任的课，这是任何教科书都无法复制的。" } },
    { icon: "⚖️", title: { en: "Values & Moral Codes", zh: "价值观与道德准则" }, body: { en: "Every culture maintains an implicit ledger of virtues and vices: honor, shame, reciprocity, purity, loyalty. These moral codes are absorbed by osmosis long before they are articulated as rules. They determine what a person finds praiseworthy, what triggers disgust, and what counts as a life well lived.", zh: "每种文化都维护着一套关于美德与恶行的隐性账簿：荣誉、羞耻、互惠、纯洁、忠诚。这些道德准则早在被明确表述为规则之前，便已通过潜移默化被吸收。它们决定着一个人认为什么值得称赞、什么会引发厌恶，以及什么才算是过好了一生。" } },
    { icon: "🕌", title: { en: "Religion & Cosmology", zh: "宗教与宇宙观" }, body: { en: "Religion supplies answers to the unanswerable: Why do people suffer? What happens after death? Is the universe just? These narratives shape risk tolerance, charity, fatalism, and the meaning-making framework that carries a person through adversity. Even secular descendants of religious cultures retain traces of those answers.", zh: "宗教为无法回答的问题提供答案：人为何受苦？死后会发生什么？宇宙是公正的吗？这些叙事塑造着风险承受能力、慈善精神、宿命论倾向，以及帮助人在逆境中寻找意义的框架。即便是宗教文化的世俗后裔，也保留着那些答案的痕迹。" } },
    { icon: "🤝", title: { en: "Individualism vs. Collectivism", zh: "个人主义与集体主义" }, body: { en: "Perhaps the single most consequential cultural axis: does the group serve the individual, or does the individual serve the group? The answer shapes everything from classroom behavior (raising your hand vs. waiting to be called) to how companies make decisions, how mental illness is treated, and what counts as a fair outcome.", zh: "这或许是影响最深远的单一文化轴线：群体服务于个人，还是个人服务于群体？这个答案塑造着从课堂行为（主动举手还是等待被点名）到企业决策方式、心理疾病的诊疗方式，乃至何为公平结果的一切。" } },
    { icon: "🍜", title: { en: "Customs & Everyday Life", zh: "风俗与日常生活" }, body: { en: "How you greet strangers, what you eat for breakfast, whether you take your shoes off indoors, when silence is comfortable — the texture of daily life is cultural code transmitted through habit. These micro-norms signal belonging, calibrate trust, and tell you who is 'us' and who is 'them' faster than any ideology.", zh: "你如何向陌生人打招呼、早餐吃什么、是否在室内脱鞋、什么时候沉默是舒适的——日常生活的质地是通过习惯传递的文化密码。这些微观规范信号着归属感，校准着信任，比任何意识形态都更快地告诉你谁是「我们」、谁是「他们」。" } },
    { icon: "🌐", title: { en: "Cultural Hybridity & Change", zh: "文化混杂与变迁" }, body: { en: "No culture is static. Migration, trade, conquest, and now algorithms create constant cultural mixing. Second-generation immigrants negotiate between heritage and host cultures simultaneously; online subcultures forge identities that cut across national lines. Yet longitudinal studies find that early-instilled core values resist change even across generations — the factory's imprint is durable.", zh: "没有任何文化是静止的。移民、贸易、征服，如今还有算法，持续创造着文化混合。第二代移民同时在母国文化与移入地文化之间周旋；网络亚文化跨越国界塑造身份认同。然而纵向研究发现，早期灌输的核心价值观即便历经数代也能抵抗改变——工厂的印记是耐久的。" } }
  ],
  questions: [
    { q: { en: "Can a person fully escape the culture they were born into?", zh: "一个人能彻底摆脱自己出生时的文化吗？" }, a: { en: "Partially. People can consciously reject surface practices, adopt new languages, and shift many values — especially when they migrate young or live in multicultural environments. But research consistently shows that deep moral intuitions and emotional responses — what feels right vs. wrong at a gut level — are highly stable. Full escape is rare; selective reshaping is common.", zh: "部分可以。人们可以有意识地拒绝表层实践，习得新语言，并转变许多价值观——尤其是在年幼时移民或生活在多元文化环境中时。但研究持续显示，深层道德直觉与情感反应——对与错的直觉感受——高度稳定。彻底逃脱极为罕见；选择性重塑则很常见。" } },
    { q: { en: "Is cultural influence deterministic — does it override individual agency?", zh: "文化影响是决定性的吗——它会凌驾于个人能动性之上吗？" }, a: { en: "No. Culture sets the current, not the destination. Within any cultural group there is enormous individual variation, and outliers who challenge prevailing norms are present in every society — they are often the agents of cultural change. The factory shapes probabilities, not certainties.", zh: "不。文化设定的是水势，而非目的地。在任何文化群体内部都存在巨大的个体差异，每个社会都有挑战主流规范的异类——他们往往是文化变革的推动者。工厂塑造的是概率，而非定数。" } }
  ],
  viz: "cards",
  vizTitle: { en: "Forces of the Culture Factory", zh: "文化工厂的作用力" },
  accent: "#e8b34a",
};
export default sec;
