import type { Section } from "@/lib/types";
const sec: Section = {
  id: "history-factory",
  num: 9,
  kicker: { en: "Factory 09 · History", zh: "工厂 09 · 历史" },
  title: { en: "The History Factory", zh: "历史工厂" },
  lead: { en: "Every generation believes it lives at the hinge of history — and every generation is correct. The year you are born assigns you a particular world, with particular threats and particular windfalls, before you have drawn your second breath.", zh: "每一代人都相信自己生活在历史的关键时刻——而每一代人都是对的。你出生的年份，在你来得及喘第二口气之前，便已将你分配给一个特定的世界，带着特定的威胁与特定的馈赠。" },
  body: [
    { en: "The sociologist Karl Mannheim argued in 1923 that a generation is not simply a cohort that shares a birth year — it is a group that shares a decisive formative experience during its most impressionable years, roughly 15–25. The events that erupt in those years — wars, economic collapses, technological ruptures, pandemics — do not merely provide historical context. They rewrite the operating assumptions through which every subsequent experience is filtered. A person who was 20 during the Great Depression interpreted risk and thrift for the rest of their life in ways that a person who was 20 in 1995 simply did not.", zh: "社会学家卡尔·曼海姆在1923年提出，一代人并不仅仅是共享同一出生年份的群体——而是在最易受影响的年龄（大约15至25岁）共同经历了决定性塑造事件的群体。在那些年间爆发的事件——战争、经济崩溃、技术断裂、瘟疫——不仅仅提供历史背景。它们重写了过滤每一次后续经历的底层操作假设。一个在大萧条时期年满20岁的人，对风险和节俭的诠释方式，是1995年那一代的20岁青年根本无法理解的。" },
    { en: "Economists call this the 'cohort effect' — the measurable impact of the macro-economic, political, and technological conditions prevailing when a person enters the labor market, forms their first political opinions, or navigates their early adult years. A study by Ulrike Malmendier and Stefan Nagel found that Americans who experienced a stock market crash during their formative years were measurably less likely to invest in equities for the rest of their lives, even decades later when their financial circumstances had improved dramatically. History does not just happen to people — it happens inside them.", zh: "经济学家将此称为“队列效应”——在一个人进入劳动市场、形成最初的政治观点或度过早期成年阶段时，主导性的宏观经济、政治和技术条件所产生的可测量影响。尤利克·马尔门迪尔和斯蒂芬·内格尔的研究发现，在成长期经历过股市崩盘的美国人，在此后的一生中投资股票的可能性明显更低，即便数十年后他们的财务状况已大幅改善。历史不仅仅降临于人们身上——它在人们内部发生。" },
    { en: "Technology is the history factory's fastest-spinning gear. The printing press, steam engine, and telegraph each created new cognitive environments — literally changing what it was possible to know and at what speed. But the acceleration has become dizzying: each of the past four technology waves (PC, internet, smartphone, AI) has landed within a single working lifetime. A person born in 1950 might incorporate all four into a single biography. The cognitive demands of each transition are distinct — the internet rewarded broad, fast, networked thinking; AI is now creating demand for judgment, synthesis, and the ability to verify rather than merely retrieve. The cohort that grows up treating AI as infrastructure will think differently from one that encountered it as a late-career disruption.", zh: "技术是历史工厂转速最快的齿轮。印刷机、蒸汽机和电报各自创造了新的认知环境——从字面意义上改变了人们能够知晓什么以及以何种速度知晓。但加速已变得令人眩目：过去四次技术浪潮（个人电脑、互联网、智能手机、人工智能），每一次都在单个职业生涯内降临。一个出生于1950年的人，可能将全部四次浪潮纳入同一部人生传记。每次转型的认知要求各不相同——互联网奖励广泛、快速、网络化的思维；人工智能如今正在创造对判断力、综合能力和验证而非仅仅检索信息能力的需求。将AI视为基础设施长大的那一代人，与将其作为职业生涯末期颠覆性力量遭遇的一代人，思维方式将截然不同。" },
    { en: "Wars and crises compress time in a different way: they create scarcity, danger, and moral urgency that forge character traits — solidarity, fatalism, post-traumatic growth, or post-traumatic stress — that outlast the crisis by decades. The economist Daron Acemoglu has shown that societies that survived extractive colonial institutions tend to have weaker state capacity and lower trust levels for generations after independence, a legacy traceable through institutional data a century later. Conversely, the post-WWII generation that came of age during the greatest economic expansion in history — the 1945–1970 boom — built the wealth, institutions, and social contracts that defined the rest of the 20th century.", zh: "战争与危机以不同的方式压缩时间：它们制造稀缺、危险和道德紧迫感，锻造出超越危机数十年的性格特质——团结、宿命论、创伤后成长或创伤后应激障碍。经济学家达龙·阿西莫格鲁证明，经历过掠夺性殖民制度的社会，在独立后数代人内往往具有更弱的国家能力和更低的信任水平，这一遗产在一个世纪后仍可在制度数据中追溯。相反，在历史上最伟大经济扩张期（1945至1970年的繁荣）成年的战后一代，建立了定义20世纪其余部分的财富、制度和社会契约。" },
    { en: "The history factory is now producing something unprecedented: since roughly 2010, each new cohort enters adulthood in a world where the information environment, social norms, and economic baseline have shifted measurably from the cohort just five years older. Sociologist Jean Twenge's data show sharp divergences in mental health, loneliness, and political identity between those who got smartphones before and after age 15 — a gap of a few years, not a generation in the classical sense. The pace of change means the concept of 'generation' may itself be obsolescing; cohort effects now operate on five-year windows rather than twenty-year ones.", zh: "历史工厂如今正在生产前所未有的东西：大约自2010年起，每一个新的队列进入成年时，都面临一个信息环境、社会规范和经济基准线相较于仅仅年长五岁的队列已发生显著变化的世界。社会学家简·特温格的数据显示，在15岁之前和之后获得智能手机的人群之间，在心理健康、孤独感和政治身份认同方面存在显著分歧——这是几年的差距，而非古典意义上的代际差距。变革的速度意味着“代际”这一概念本身或许正在过时；队列效应现在在五年窗口而非二十年窗口内运作。" }
  ],
  cards: [
    { icon: "⚔️", title: { en: "Born 1900 · Age of Total War", zh: "生于1900年·总体战时代" }, body: { en: "A 1900 birth meant navigating two World Wars before age 50. The defining cognitive legacy: that civilization itself is fragile, institutions can collapse overnight, and security must be hoarded rather than assumed. This cohort invented the welfare state, the United Nations, and the nuclear deterrent — all responses to having watched order dissolve.", zh: "生于1900年意味着在50岁之前要穿越两次世界大战。留下的决定性认知遗产：文明本身是脆弱的，制度可以在一夜之间崩塌，安全必须积累而非视为理所当然。这一代人发明了福利国家、联合国和核威慑——都是亲眼目睹秩序瓦解后的应对之策。" } },
    { icon: "🌱", title: { en: "Born 1945 · The Great Prosperity", zh: "生于1945年·大繁荣时代" }, body: { en: "Postwar baby boomers entered a labor market of near-full employment, rising real wages, and expanding higher education. The defining assumption: hard work reliably produces upward mobility. This cohort's wealth expectations — a pension, a home, early retirement — became the baseline that later generations were measured against and found wanting.", zh: "战后婴儿潮一代进入了一个近乎充分就业、实际工资上涨、高等教育扩张的劳动市场。决定性的假设：努力工作可以可靠地带来向上流动。这一代人的财富预期——养老金、住房、提前退休——成为后续几代人被比照衡量并被发现不足的基准线。" } },
    { icon: "💻", title: { en: "Born 1980 · The PC & Globalization Cohort", zh: "生于1980年·个人电脑与全球化世代" }, body: { en: "Millennials entered the internet as teenagers and the labor market during the 2008 financial crisis. They absorbed both the optimism of the networked world and the scar tissue of a crash that reset their wealth trajectory relative to their parents. Student debt, delayed homeownership, and tech-sector stratification are cohort-specific artifacts — not individual failures.", zh: "千禧一代在青少年时期接触互联网，并在2008年金融危机期间进入劳动市场。他们既吸收了网络世界的乐观主义，也带着一场重置了其相对于父辈财富轨迹的崩盘所留下的疤痕组织。学生债务、推迟购房和科技行业分层，是这一队列特有的产物——而非个人的失败。" } },
    { icon: "📱", title: { en: "Born 1995 · Digital Natives", zh: "生于1995年·数字原住民" }, body: { en: "Gen Z entered social media during their most neurologically impressionable years. They are the first cohort for whom anxiety, loneliness, and political polarization have been measurably worse than for the cohort just a decade older — correlating with the smartphone's mass adoption. They also inherit the highest student debt, the most precarious labor market, and the sharpest climate awareness of any previous generation.", zh: "Z世代在神经系统最易受影响的年龄进入了社交媒体。他们是第一个其焦虑、孤独感和政治极化程度可测量地比仅年长十年的一代人更严重的队列——这与智能手机的大规模普及相关。他们还继承了迄今为止最高的学生债务、最不稳定的劳动市场，以及任何前代都不曾有过的最强烈的气候危机意识。" } },
    { icon: "🤖", title: { en: "Born 2010 · The AI Generation", zh: "生于2010年·人工智能世代" }, body: { en: "This cohort will form its basic cognitive assumptions — about what intelligence is, what work means, what a reliable source looks like — in a world where AI composes, codes, and reasons. They will likely be the last to remember a world before ubiquitous AI, and the first to treat AI as simply ambient. Their labor market will be unrecognizable to anyone born before 1990.", zh: "这一队列将在人工智能撰写、编程和推理的世界中，形成其对智能是什么、工作意味着什么、可靠信息源看起来如何等问题的基本认知假设。他们很可能是最后一批记得无处不在的AI出现之前那个世界的人，也是第一批将AI视为环境本身的人。他们将面临的劳动市场，对于任何出生在1990年之前的人来说，都将是无法辨认的。" } },
    { icon: "🔮", title: { en: "Born 2023 · Uncertain Horizon", zh: "生于2023年·不确定的地平线" }, body: { en: "What will define the 2023 cohort is not yet knowable — which is itself a data point. The rate of change has become so fast that the world into which they will graduate (circa 2045) may involve technologies, climate conditions, and geopolitical alignments we cannot reliably forecast. For the first time in history, generational preparation is genuinely open-ended.", zh: "定义2023年出生队列的，目前尚不可知——这本身就是一个数据点。变化的速度已变得如此之快，以至于他们将毕业进入的世界（大约2045年）可能涉及我们无法可靠预测的技术、气候条件和地缘政治格局。这是历史上第一次，代际准备真正成为开放性的命题。" } }
  ],
  questions: [
    { q: { en: "Are generational differences real, or is every generation just 'kids these days'?", zh: "代际差异是真实的，还是每一代人都只是「现在的年轻人」？" }, a: { en: "Both contain truth. Older generations have always complained about younger ones — this is well-documented and partly reflects normal aging. But longitudinal data tracking the same individuals over time confirm real cohort effects: people who grew up during recessions genuinely do save more; people who experienced war genuinely do differ on authoritarianism tolerance. The signal is real, even if it is frequently overstated.", zh: "两者都有一定道理。年长一代总是抱怨年轻一代——这有充分的文献记录，且部分反映了正常的老龄化心理。但追踪同一群人随时间变化的纵向数据证实了真实的队列效应：在经济衰退期成长的人确实储蓄更多；经历过战争的人在对威权主义的容忍度上确实有所不同。这个信号是真实的，尽管它经常被夸大。" } },
    { q: { en: "Can individuals transcend their historical moment, or are they prisoners of their era?", zh: "个人能超越自己所处的历史时刻吗，还是他们是时代的囚徒？" }, a: { en: "History sets the terrain; individuals navigate it with varying skill. Outliers exist in every era — people who resisted fascism when their neighbors collaborated, who invested when their generation hoarded, who learned to code at 60. But the distribution of outcomes within a cohort is shaped powerfully by what the era makes easy or hard, rewarded or punished. The history factory determines the odds; the person determines where within that distribution they end up.", zh: "历史设定地形；个人以不同的技巧在其中穿行。每个时代都有异类——在邻居合作时抵抗法西斯主义的人，在本代人囤积时投资的人，在60岁时学会编程的人。但一个队列内部的结果分布，深受时代将何事变得容易或困难、奖励或惩罚这一因素的强力塑造。历史工厂决定赔率；人自身决定他们最终落在那个分布的哪个位置。" } }
  ],
  viz: "timeline",
  vizTitle: { en: "Birth-Year Cohorts: How the Era Shapes Destiny", zh: "出生年代队列：时代如何塑造命运" },
  vizData: [
    { label: { en: "Born 1900 · Total War Generation", zh: "生于1900年·总体战一代" }, year: 1900, note: { en: "Came of age into WWI (1914–1918) and WWII (1939–1945). Formative experience: institutional collapse, mass death, rationing. Legacy: welfare state, UN, nuclear deterrence — architecture of the postwar order.", zh: "在一战（1914—1918年）和二战（1939—1945年）中成年。塑造性经历：制度崩塌、大规模死亡、物资配给。遗产：福利国家、联合国、核威慑——战后秩序的建筑框架。" } },
    { label: { en: "Born 1945 · Postwar Boom Cohort", zh: "生于1945年·战后繁荣世代" }, year: 1945, note: { en: "Grew up in the longest peacetime expansion in Western history. Real wages rose every decade; university attendance tripled. Formative assumption: effort reliably buys upward mobility. Built the suburbs, the pension system, and the mass consumer economy.", zh: "在西方历史上最长的和平扩张期成长。实际工资每十年上涨；大学入学率提高三倍。塑造性假设：努力可以可靠地换来向上流动。建造了郊区、养老金体系和大众消费经济。" } },
    { label: { en: "Born 1980 · PC & Globalization Cohort", zh: "生于1980年·个人电脑与全球化世代" }, year: 1980, note: { en: "Adolescence coincided with the PC revolution; early adulthood with the internet boom and the 2008 financial crisis. Scarred by the crash: delayed homeownership, student debt. But also the first generation to build global careers from a laptop.", zh: "青春期恰逢个人电脑革命；成年初期恰逢互联网繁荣和2008年金融危机。被危机留下疤痕：推迟购房、学生债务。但也是第一批用笔记本电脑构建全球职业生涯的一代。" } },
    { label: { en: "Born 1995 · Digital Native Generation", zh: "生于1995年·数字原住民世代" }, year: 1995, note: { en: "First cohort to grow up with smartphones from early adolescence. Mental health data show measurable increase in anxiety, depression, and loneliness vs. earlier cohorts — correlated with social media adoption. Also the most globally connected, politically activated, and climate-aware generation on record.", zh: "第一批从青春期早期就拥有智能手机的队列。心理健康数据显示，与更早的队列相比，焦虑、抑郁和孤独感可测量地增加——与社交媒体普及相关。同时也是有记录以来全球连接度最高、政治参与度最强、气候意识最深的一代。" } },
    { label: { en: "Born 2010 · Pandemic & AI Cohort", zh: "生于2010年·疫情与人工智能世代" }, year: 2010, note: { en: "Spent critical early schooling years during COVID-19 lockdowns (2020–2022), with documented learning-loss effects. Will enter the labor market during AI's mass deployment phase. Their definition of 'normal work' and 'reliable knowledge' will be shaped by AI from the start.", zh: "在新冠疫情封锁期间（2020—2022年）度过了关键的早期学校教育年份，记录在案的学习损失效应显著。将在人工智能大规模部署阶段进入劳动市场。他们对「正常工作」和「可靠知识」的定义，从一开始就将被人工智能塑造。" } },
    { label: { en: "Born 2023 · Open Horizon", zh: "生于2023年·开放地平线" }, year: 2023, note: { en: "The world of their adulthood (circa 2040–2050) involves technologies not yet invented, climate disruptions not yet peaked, and geopolitical alignments not yet settled. For the first time, the history factory cannot pre-load a reliable map — this generation will navigate by instruments that do not yet exist.", zh: "他们成年时（约2040—2050年）的世界，涉及尚未发明的技术、尚未达到峰值的气候扰动，以及尚未稳定的地缘政治格局。历史上第一次，历史工厂无法预装一张可靠的地图——这一代人将用尚不存在的仪器导航。" } }
  ],
  quote: { text: { en: "\"The most important thing about a man is what he takes for granted.\"", zh: "「一个人最重要的事，是他视为理所当然的那些东西。」" }, attr: { en: "— Alfred North Whitehead, adapted", zh: "— 改编自阿尔弗雷德·诺思·怀特海" } },
  accent: "#f0a04a",
};
export default sec;
