import type { Section } from "@/lib/types";

const sec: Section = {
  id: "first-cell",
  num: 1,
  kicker: { en: "Factory 01 · Origin", zh: "工厂 01 · 起源" },
  title: { en: "The First Cell", zh: "第一个细胞" },
  lead: { en: "Every human being begins as a single cell smaller than the period at the end of this sentence — and inside that cell is a complete, unrepeatable blueprint for a person.", zh: "每一个人类生命，都始于一个比句号还小的细胞——而在那个细胞里，藏着一份完整的、独一无二的生命蓝图。" },
  body: [
    { en: "At the moment of fertilization, a sperm carrying 23 chromosomes fuses with an egg carrying another 23, producing a zygote with a full complement of 46 chromosomes arranged into 23 pairs. This is not a gradual negotiation: the merger is decisive, chemical, and complete within hours. The resulting genome — roughly 3.2 billion base pairs of DNA — has never existed before and will never exist again. Two lineages, each tracing back hundreds of millions of years, converge to produce a third individual who belongs entirely to neither.", zh: "在受精的瞬间，一个携带23条染色体的精子与同样携带23条染色体的卵子融合，形成一个拥有完整46条染色体的受精卵。这不是一个渐进的谈判过程：合并是决定性的、化学性的，并在数小时内完成。由此产生的基因组——大约32亿个碱基对——从未在历史上存在过，也永远不会再次出现。两条各自可追溯数亿年的血脉，在此汇聚，孕育出一个完全属于自己的第三个个体。" },
    { en: "Inside the nucleus, the 46 chromosomes are not passive storage. Chromosome 1, the largest, contains roughly 2,000 genes. Chromosome 21, one of the smallest, contains around 200. Each gene is a recipe — a sequence of nucleotide letters that, when read by molecular machinery, produces a protein with a specific shape and function. But genes are also deeply social: most traits are not controlled by a single gene but by thousands acting in concert, their combined effect shaped further by the environment that the organism encounters across its entire life.", zh: "在细胞核内，46条染色体并非被动的储存装置。最大的1号染色体约含2000个基因，而最小的21号染色体约含200个。每个基因都是一份配方——一段核苷酸序列，当被分子机器读取时，会产生具有特定形状和功能的蛋白质。但基因也是高度「社交」的：大多数性状并非由单一基因控制，而是由数千个基因协同作用，其综合效果还会被个体一生中所遭遇的环境进一步塑造。" },
    { en: "The egg contributes something the sperm cannot: mitochondria. These organelles, which power every cell in the body, carry their own small genome of 37 genes, passed exclusively through the maternal line. Mitochondrial DNA mutates slowly and predictably, making it an extraordinarily precise tool for tracing ancestry — every living human shares a common maternal ancestor, “Mitochondrial Eve,” estimated to have lived in Africa roughly 150,000 to 200,000 years ago. You carry her signature in every cell.", zh: "卵子贡献了一样精子无法提供的东西：线粒体。这些为体内每个细胞提供能量的细胞器拥有自己的小基因组，共37个基因，仅通过母系遗传。线粒体DNA变异缓慢且规律，使其成为追溯祖先的极其精准的工具——所有现存人类都拥有一位共同的母系祖先，即「线粒体夏娃」，估计生活在距今约15万至20万年前的非洲。你的每个细胞里，都携带着她的印记。" },
    { en: "The zygote's first act is to divide. Within 30 hours it becomes two cells; within three days, a cluster of eight; by day five, a hollow sphere of roughly 100 cells called a blastocyst. None of these early cells has yet committed to a specific fate: they remain pluripotent, capable of becoming almost any tissue in the body. This is the brief, extraordinary moment before the manufacturing process specializes — before one group of cells is told to become a nervous system, another a heart, another skin. The entire complexity of the adult human body originates from this window of radical openness.", zh: "受精卵的第一个行动就是分裂。在30小时内它变成两个细胞；三天内变成八个细胞的团块；到第五天，形成一个由约100个细胞组成的空心球体，称为囊胚。这些早期细胞尚未确定各自的命运：它们保持着多能性，几乎可以发育成身体的任何组织。这是制造过程开始专化之前短暂而非凡的时刻——在一组细胞被「告知」要成为神经系统、另一组成为心脏、另一组成为皮肤之前。成人身体的全部复杂性，都源于这个彻底开放的窗口。" },
    { en: "What makes the first cell so philosophically startling is not its chemistry but its combinatorics. Each parent can produce more than 8 million genetically distinct gametes through recombination alone; the number of possible offspring from any two parents exceeds the number of atoms in the observable universe. The person you are was never inevitable. You are, in the most literal sense, an astronomical improbability that somehow arrived.", zh: "让第一个细胞在哲学上令人震惊的，不是其化学性质，而是其组合学意义。每位父母仅通过重组就能产生超过800万种基因各异的配子；任意两位父母所能产生的可能后代数量，超过了可观测宇宙中的原子总数。你这个人，从未是必然的存在。从最字面的意义上说，你是一个以某种方式降临的天文数字级别的小概率事件。" }
  ],
  cards: [
    { icon: "🧬", title: { en: "The Zygote", zh: "受精卵" }, body: { en: "A single fertilized cell containing 46 chromosomes — 23 from each parent — and the complete genetic instruction set for a unique human being.", zh: "一个受精细胞，含有46条染色体——父母各提供23条——以及一套完整的基因指令，可以构建一个独一无二的人。" } },
    { icon: "🌀", title: { en: "Chromosomes", zh: "染色体" }, body: { en: "46 tightly coiled packages of DNA, arranged in 23 pairs. Chromosomes 1–22 are autosomes; the 23rd pair determines biological sex (XX or XY).", zh: "46条紧密卷曲的DNA包装体，排列成23对。1至22号为常染色体，第23对决定生物学性别（XX或XY）。" } },
    { icon: "🔬", title: { en: "DNA Base Pairs", zh: "DNA碱基对" }, body: { en: "About 3.2 billion base pairs encode the human genome. Less than 2% are protein-coding genes; the rest regulate, structure, and coordinate — and are still being decoded.", zh: "约32亿个碱基对编码了人类基因组。不足2%是编码蛋白质的基因，其余负责调控、结构和协调——且仍在被科学界持续解读。" } },
    { icon: "⚡", title: { en: "Mitochondria & Maternal Line", zh: "线粒体与母系遗传" }, body: { en: "Mitochondria — the cell's power plants — carry their own 37-gene genome passed only through the mother. Tracing this DNA reveals a shared maternal ancestor some 150,000–200,000 years ago.", zh: "线粒体——细胞的「发电厂」——携带着自己拥有37个基因的基因组，只通过母亲遗传。追踪这段DNA，可以揭示一位生活在约15万至20万年前的共同母系祖先。" } },
    { icon: "🎲", title: { en: "Recombination", zh: "基因重组" }, body: { en: "Before sperm and egg form, chromosomes swap segments in a process called crossover. Each parent can produce over 8 million genetically distinct gametes — so no two siblings are ever the same.", zh: "在精子和卵子形成之前，染色体通过「交叉互换」过程交换片段。每位父母可产生超过800万种基因各异的配子——因此任何两个兄弟姐妹都不可能完全相同。" } },
    { icon: "🌱", title: { en: "Pluripotency", zh: "多能性" }, body: { en: "For the first five days after fertilization, every cell in the embryo can still become any tissue. This brief window of radical openness is the origin of regenerative medicine and the stem-cell field.", zh: "受精后最初五天内，胚胎中的每个细胞仍可发育为任何组织。这个短暂的彻底开放窗口，是再生医学和干细胞领域的起源。" } }
  ],
  questions: [
    { q: { en: "If two parents have a child, how many genetically unique children could they theoretically produce?", zh: "如果两位父母生育孩子，理论上他们能产生多少基因独特的后代？" }, a: { en: "The combinatorics are staggering: more possible genomes than atoms in the observable universe. This is why full siblings share roughly 50% of variable DNA but are never genetically identical (except identical twins, who start from the same zygote).", zh: "其组合数量令人叹为观止：可能的基因组数量超过可观测宇宙中的原子总数。这就是为什么同胞兄弟姐妹共享约50%的可变DNA，却从不完全相同（同卵双胞胎除外，他们来自同一受精卵）。" } },
    { q: { en: "Is all of my DNA from my parents?", zh: "我的所有DNA都来自我的父母吗？" }, a: { en: "Almost. But roughly 1 in every 100 million base pairs is a de novo mutation — a new change that arose in your parents' germ cells and was not present in your grandparents. You carry some genetic novelty the world has never seen.", zh: "几乎全是。但大约每1亿个碱基对中有1个是新发突变——一种在你父母的生殖细胞中出现的新变化，你的祖父母并没有。你携带着一些世界从未见过的基因新颖性。" } }
  ],
  viz: "constellation",
  vizTitle: { en: "DNA Explorer: The Architecture of the First Cell", zh: "DNA探索器：第一个细胞的结构" },
  vizData: [
    { label: { en: "Chromosome 1", zh: "1号染色体" }, group: "Genome", note: { en: "The largest human chromosome; contains ~2,000 genes including many linked to cancer susceptibility and neurological function.", zh: "最大的人类染色体，含约2000个基因，其中许多与癌症易感性和神经系统功能相关。" } },
    { label: { en: "Chromosome 21", zh: "21号染色体" }, group: "Genome", note: { en: "One of the smallest autosomes (~200 genes). Trisomy of chromosome 21 produces Down syndrome, the most common chromosomal condition in live births.", zh: "最小的常染色体之一（约200个基因）。21号染色体三体导致唐氏综合征，是活产中最常见的染色体异常。" } },
    { label: { en: "Sex Chromosomes (XY / XX)", zh: "性染色体（XY / XX）" }, group: "Genome", note: { en: "The 23rd pair determines biological sex. Sperm carrying X or Y chromosome determine the outcome; the egg always contributes X.", zh: "第23对染色体决定生物学性别。携带X或Y染色体的精子决定结果；卵子始终提供X染色体。" } },
    { label: { en: "DNA Double Helix", zh: "DNA双螺旋" }, group: "Molecule", note: { en: "Two antiparallel strands of nucleotides bonded by base-pairing (A–T, C–G). The sequence of these bases is the genetic code, read in triplets called codons.", zh: "两条反向平行的核苷酸链通过碱基配对（A–T，C–G）连接。这些碱基的序列就是遗传密码，以称为「密码子」的三联体形式被读取。" } },
    { label: { en: "Gene", zh: "基因" }, group: "Molecule", note: { en: "A segment of DNA encoding a functional product — usually a protein. Humans carry ~20,000 protein-coding genes, fewer than a water flea. Regulation, not gene count, explains complexity.", zh: "编码功能性产物（通常是蛋白质）的一段DNA。人类约有2万个蛋白质编码基因，比水蚤还少。复杂性的根源在于基因调控，而非基因数量。" } },
    { label: { en: "Mitochondria", zh: "线粒体" }, group: "Organelle", note: { en: "Ancient bacterial endosymbionts that produce ATP (cellular energy). They carry 37 genes in a separate circular genome inherited exclusively through the mother — a living record of maternal ancestry.", zh: "古代细菌内共生体，负责产生ATP（细胞能量）。它们在独立的环形基因组中携带37个基因，只通过母亲遗传——是母系祖先的活体记录。" } },
    { label: { en: "Centromere", zh: "着丝粒" }, group: "Structure", note: { en: "The pinch-point of each chromosome, essential for accurate segregation during cell division. Errors here produce aneuploidy — missing or extra chromosomes in daughter cells.", zh: "每条染色体的「收缩点」，对于细胞分裂时染色体的准确分配至关重要。此处的错误会导致非整倍性——子代细胞中染色体缺失或多余。" } },
    { label: { en: "Telomere", zh: "端粒" }, group: "Structure", note: { en: "Protective caps at chromosome ends, like the plastic tip on a shoelace. They shorten with every cell division; telomere length is associated with biological aging and cellular senescence.", zh: "染色体末端的保护帽，如同鞋带末端的塑料套。每次细胞分裂后端粒都会缩短；端粒长度与生物衰老和细胞衰老相关。" } },
    { label: { en: "Fertilization", zh: "受精" }, group: "Event", note: { en: "The moment sperm and egg fuse, combining two sets of 23 chromosomes into one diploid genome. Triggers cortical reaction in the egg — a biochemical lock that prevents other sperm from entering.", zh: "精子与卵子融合的瞬间，将两组各23条染色体合并为一个二倍体基因组。这触发了卵子的皮质反应——一种防止其他精子进入的生化锁。" } },
    { label: { en: "Zygote", zh: "受精卵" }, group: "Event", note: { en: "The first cell of a new human: totipotent, containing the full 46-chromosome genome. Within 30 hours it undergoes its first division, launching a cascade that will produce ~37 trillion cells.", zh: "新人类的第一个细胞：全能的，含有完整的46条染色体基因组。在30小时内进行第一次分裂，启动将产生约37万亿个细胞的级联过程。" } },
    { label: { en: "Recombination", zh: "基因重组" }, group: "Event", note: { en: "During meiosis, homologous chromosomes exchange segments at points called chiasmata. This reshuffling ensures every gamete — and every child — is genetically unique.", zh: "在减数分裂过程中，同源染色体在称为「交叉点」的位置交换片段。这种重新洗牌确保了每个配子——以及每个孩子——在遗传上都是独特的。" } },
    { label: { en: "Blastocyst", zh: "囊胚" }, group: "Event", note: { en: "By day 5, the embryo is a hollow sphere of ~100 pluripotent cells. The inner cell mass will become the embryo proper; the outer layer becomes the placenta. Implantation into the uterine wall follows.", zh: "到第5天，胚胎是一个由约100个多能细胞组成的空心球体。内细胞团将发育为胚胎本身；外层成为胎盘。随后发生植入子宫壁的过程。" } }
  ],
  quote: { text: { en: "“You are the one in a million — no, the one in ten billion trillion — who got to be here.”", zh: "「你是百万之一——不，万亿分之一——得以来到这个世界的那一个。」" }, attr: { en: "— Bill Bryson, A Short History of Nearly Everything", zh: "— 比尔·布莱森，《万物简史》" } },
  accent: "#4fd6c4",
};

export default sec;
