import type { Section } from "@/lib/types";

const sec: Section = {
  id: "genetic-factory",
  num: 2,
  kicker: { en: "Factory 02 · Inheritance", zh: "工厂 02 · 遗传" },
  title: { en: "The Genetic Factory", zh: "基因工厂" },
  lead: { en: "Your genome is not a sentence that reads one way — it is a vast library in constant dialogue with the world around it, where predisposition is never the same as destiny.", zh: "你的基因组不是一句只能被单一解读的话——它是一座与外部世界持续对话的庞大图书馆，基因倾向永远不等于命运。" },
  body: [
    { en: "Behavioral genetics attempts to partition human variation into two broad sources: heredity and environment. The tool for doing this is the twin study — comparing identical twins (who share nearly 100% of their DNA) with fraternal twins (who share about 50%). When identical twins raised apart are more similar than fraternal twins raised together, heritability is implied. Across hundreds of studies spanning a century, heritability estimates for most psychological traits cluster between 30% and 60%. This means genes explain a substantial share of why people differ — but never the whole story, and never for any specific individual.", zh: "行为遗传学试图将人类差异的来源分为两大类：遗传和环境。用于研究的工具是双胞胎研究——比较同卵双胞胎（共享近100%的DNA）与异卵双胞胎（共享约50%的DNA）。当分开抚养的同卵双胞胎比一起抚养的异卵双胞胎更相似时，就意味着遗传力的存在。在跨越一个世纪的数百项研究中，大多数心理特质的遗传力估计值在30%至60%之间。这意味着基因在解释人们差异方面起着重要作用——但从不是全部，也永远无法预测某一具体个体。" },
    { en: "Almost every complex human trait — height, weight, temperament, general cognitive ability — is polygenic: influenced not by one gene but by thousands of variants, each contributing a tiny fraction of a percent to overall variation. A polygenic score for height, for example, aggregates the effects of more than 10,000 genetic variants and can explain roughly 25–40% of the variance in height within a population. Polygenic scores for educational attainment or cognitive performance are improving but explain considerably less variance — in the range of 10–15% — and are highly sensitive to the population in which they were derived. They describe statistical tendencies across groups, not fates for individuals.", zh: "几乎所有复杂的人类特质——身高、体重、性情、一般认知能力——都是多基因的：受数千个变异影响，每个变异对总体差异的贡献只有极小的百分比。例如，身高的多基因评分汇总了超过1万个遗传变异的效应，可以解释群体内身高差异的约25%至40%。教育程度或认知表现的多基因评分正在改进，但解释的差异仍然有限——在10%至15%的范围内——且对其来源人群高度敏感。它们描述的是群体的统计趋势，而非个体的命运。" },
    { en: "The heritability of general cognitive ability (commonly called g or IQ) has been studied more intensively than almost any other trait, and the findings are routinely misunderstood. Twin and adoption studies suggest heritability of around 50–80% in adults in affluent, high-resource environments. But several critical caveats apply. First, heritability is not fixed: it is higher in wealthy environments because environmental variation is compressed, and lower in disadvantaged environments where poverty, malnutrition, and toxic stress suppress the expression of genetic potential. Second, heritability tells us nothing about group differences in test scores — it is a within-group statistic, never a between-group one. Third, IQ scores are sensitive to education, nutrition, and cultural familiarity with testing formats. No honest scientist claims genes determine intelligence in any simple or fixed way.", zh: "一般认知能力（通常称为g因子或智商）的遗传力是研究最密集的特质之一，但其研究结果常常被误解。双胞胎和收养研究表明，在富裕、高资源环境中，成年人的遗传力约为50%至80%。但有几点重要警告。第一，遗传力并非固定：在富裕环境中更高，因为环境差异被压缩；在不利环境中更低，因为贫困、营养不良和毒性应激会抑制遗传潜力的表达。第二，遗传力无法解释群体间的测试分数差异——它是组内统计量，永远不是组间统计量。第三，智商分数对教育、营养和文化对测试形式的熟悉程度很敏感。没有诚实的科学家会声称基因以任何简单或固定的方式决定智力。" },
    { en: "Personality research — anchored in the Five Factor Model of openness, conscientiousness, extraversion, agreeableness, and neuroticism — finds heritability in the 40–60% range for each trait. These predispositions are real and stable across decades, but they interact continuously with environment. An introverted child raised in a stimulating social household may develop different social fluency than one raised in isolation. Crucially, gene-environment interaction runs in both directions: genes influence which environments we seek out (gene-environment correlation), and environments modulate which genes are expressed (epigenetics). The genome is not a rigid programme; it is a set of conditional instructions.", zh: "个性研究——以开放性、尽责性、外向性、宜人性和神经质这五大人格模型为基础——发现每种特质的遗传力在40%至60%之间。这些倾向是真实的，在数十年内保持稳定，但它们与环境持续互动。一个在充满社交刺激的家庭中长大的内向儿童，可能会比在孤立环境中长大的儿童发展出不同的社交流畅度。关键是，基因-环境互动是双向的：基因影响我们寻求哪些环境（基因-环境相关），而环境调控哪些基因被表达（表观遗传学）。基因组不是一个固化的程序，而是一套条件性指令。" },
    { en: "The deepest misuse of heritability data is the leap from population statistics to individual prescription. A heritability of 80% for a trait does not mean 80% of your version of that trait came from your genes. It means that across the studied population, 80% of the observed variation was associated with genetic variation. You are not a population average. Your genes set a range of probable outcomes; your development, your choices, your context, and a great deal of chance determine where within that range you actually land. Predisposition is real. Destiny, in any genetic sense, is not.", zh: "对遗传力数据最严重的误用，是从群体统计数据跳跃到对个人的预言。某特质80%的遗传力并不意味着你的该特质有80%来自你的基因。它的意思是，在研究的群体中，80%的观察到的差异与遗传变异相关。你不是群体平均值。你的基因设定了一系列可能的结果范围；你的发育、选择、背景以及大量的偶然因素，决定了你实际落在那个范围内的哪个位置。遗传倾向是真实存在的。而任何遗传意义上的「命运」，则并不存在。" }
  ],
  cards: [
    { icon: "📊", title: { en: "Heritability", zh: "遗传力" }, body: { en: "A statistical measure of how much variation in a trait, within a specific population at a specific time, is associated with genetic differences. It ranges from 0 to 1 — but it is always a population estimate, never a personal one.", zh: "一种统计量，衡量在特定时间的特定群体中，某特质差异有多少与遗传差异相关。范围从0到1——但它始终是群体估计值，而非个人估计值。" } },
    { icon: "🌐", title: { en: "Polygenic Traits", zh: "多基因性状" }, body: { en: "Height, weight, skin tone, and cognitive ability are each influenced by thousands of genetic variants, not a single gene. Most variants have tiny individual effects; their aggregate shapes the distribution of the trait across a population.", zh: "身高、体重、肤色和认知能力各自受数千个遗传变异的影响，而非单一基因。大多数变异的个体效应极小；它们的累积效应塑造了该特质在群体中的分布。" } },
    { icon: "🧠", title: { en: "Intelligence: Carefully", zh: "智力：需审慎对待" }, body: { en: "Twin studies suggest 50–80% heritability for general cognitive ability in affluent adults — but heritability shrinks in low-resource environments, IQ is sensitive to education and nutrition, and heritability is a within-group statistic that cannot explain group differences. Predisposition exists; determinism does not.", zh: "双胞胎研究表明，在富裕成人中，一般认知能力的遗传力约为50%至80%——但在低资源环境中遗传力会缩小，智商对教育和营养敏感，且遗传力是组内统计量，无法解释群体间差异。遗传倾向存在；遗传决定论则不成立。" } },
    { icon: "🎭", title: { en: "Personality", zh: "人格" }, body: { en: "The Big Five personality traits (openness, conscientiousness, extraversion, agreeableness, neuroticism) each show heritability of 40–60%. They are stable across decades yet modulated by experience — a genetic temperament that environment continuously sculpts.", zh: "大五人格特质（开放性、尽责性、外向性、宜人性、神经质）各自的遗传力为40%至60%。它们在数十年内保持稳定，但受经历调节——基因赋予的气质被环境持续雕刻。" } },
    { icon: "⚠️", title: { en: "Predisposition ≠ Destiny", zh: "遗传倾向 ≠ 命运" }, body: { en: "A high polygenic risk score for depression means an elevated probability — not a sentence. BRCA1 mutations dramatically raise breast-cancer risk, yet many carriers never develop cancer. Genes load the dice; they do not roll them.", zh: "抑郁症的高多基因风险评分意味着概率升高——而非判决。BRCA1基因突变会大幅增加乳腺癌风险，但许多携带者从未患癌。基因装填了骰子；但并非由它们来掷出。" } },
    { icon: "🔄", title: { en: "Gene × Environment", zh: "基因与环境的交互" }, body: { en: "Genes and environment are not independent forces — they interact. Sensitive children may thrive in nurturing homes and suffer in harsh ones more than less-sensitive peers (differential susceptibility). Epigenetics shows that experience can switch genes on or off without changing the DNA sequence.", zh: "基因与环境并非独立的力量——它们相互作用。敏感型儿童在温暖家庭中可能比不那么敏感的同龄人更为茁壮，而在严苛环境中则更受损害（差异易感性）。表观遗传学表明，经历可以在不改变DNA序列的情况下开启或关闭基因。" } },
    { icon: "🌍", title: { en: "Population Genetics", zh: "群体遗传学" }, body: { en: "All living humans are remarkably similar genetically: two randomly chosen humans share about 99.9% of their DNA. The small fraction of variation is the raw material that heritability studies analyze — and context always shapes how that variation expresses.", zh: "所有现存人类在遗传上非常相似：随机选取的两个人约共享99.9%的DNA。那一小部分变异是遗传力研究分析的原材料——而背景始终塑造着这些变异的表达方式。" } },
    { icon: "🔬", title: { en: "GWAS & Polygenic Scores", zh: "全基因组关联研究与多基因评分" }, body: { en: "Genome-wide association studies scan millions of genetic variants across hundreds of thousands of people to find statistical associations with traits. The resulting polygenic scores are genuinely predictive at the population level but explain a modest fraction of individual variation — and perform worst in non-European populations due to training-data bias.", zh: "全基因组关联研究在数十万人中扫描数百万个遗传变异，以找到与特质的统计关联。由此产生的多基因评分在群体层面具有真正的预测价值，但仅能解释个体差异的一小部分——且由于训练数据偏差，在非欧洲人群中表现最差。" } }
  ],
  questions: [
    { q: { en: "If a trait is 70% heritable, does that mean 70% of my score on that trait came from my genes?", zh: "如果一个特质的遗传力为70%，这是否意味着我在该特质上的得分有70%来自我的基因？" }, a: { en: "No — this is the most common misreading of heritability. The 70% refers to the fraction of variation across the studied population that correlates with genetic variation. Your specific score is the product of your unique genes, development, environment, and chance. Heritability says nothing about you as an individual.", zh: "不——这是对遗传力最常见的误读。这70%是指研究群体中与遗传变异相关的差异比例。你的具体得分是你独特的基因、发育、环境和偶然性共同作用的结果。遗传力对你作为个体没有任何说明。" } },
    { q: { en: "Are there genes for success?", zh: "存在「成功基因」吗？" }, a: { en: "Not in any simple sense. Traits associated with professional achievement — conscientiousness, cognitive ability, openness to experience — have moderate heritability, but the path from genes to success runs through education, environment, networks, timing, and a good deal of luck. No polygenic score predicts an individual's life outcome reliably.", zh: "没有任何简单意义上的「成功基因」。与职业成就相关的特质——尽责性、认知能力、经验开放性——具有中等遗传力，但从基因到成功的路径需要经过教育、环境、人际网络、时机和大量运气。没有任何多基因评分能可靠地预测个体的人生结果。" } },
    { q: { en: "Can genes explain differences in average test scores between racial or ethnic groups?", zh: "基因能解释种族或族裔群体间平均测试分数的差异吗？" }, a: { en: "No — heritability is a within-group statistic and cannot be used to explain between-group differences. The observed gaps in test scores are far better explained by historical and ongoing disparities in education, wealth, nutrition, stress, and cultural familiarity with tests. There is no credible scientific evidence that genetic differences between racial groups drive measured cognitive differences.", zh: "不——遗传力是组内统计量，不能用于解释组间差异。测试分数上观察到的差距，更好地被教育、财富、营养、压力和对测试文化的熟悉程度方面长期存在的不平等所解释。没有可信的科学证据表明种族群体间的遗传差异驱动了测量到的认知差异。" } }
  ],
  viz: "cards",
  vizTitle: { en: "Key Concepts in Behavioral Genetics", zh: "行为遗传学的核心概念" },
  accent: "#6ee0a0",
};

export default sec;
