import type { Section } from "@/lib/types";
const sec: Section = {
  id: "geography-factory",
  num: 8,
  kicker: { en: "Factory 08 · Geography", zh: "工厂 08 · 地理" },
  title: { en: "The Geography Factory", zh: "地理工厂" },
  lead: { en: "The single most powerful predictor of a child's life outcomes is not their IQ, their parents' character, or their own ambition — it is the GPS coordinates of their birth.", zh: "预测一个孩子人生结果最有力的单一变量，不是智商、父母品格，也不是本人的雄心——而是出生时的GPS坐标。" },
  body: [
    { en: "Raj Chetty and colleagues at Opportunity Insights have demonstrated that in the United States alone, a child's neighborhood at age 5 predicts their adult income, incarceration rate, and likelihood of upward mobility more reliably than almost any other measurable factor. Globally, the gaps are even more stark: a child born in Norway has a life expectancy roughly 30 years longer than one born in the Central African Republic, and will receive an education worth an estimated 14 additional years of schooling quality. The address is not the person — but it is the scaffolding within which the person is assembled.", zh: "拉吉·切蒂及其“机会洞察”团队的研究表明，仅在美国，一个孩子5岁时所在的社区，就比几乎任何其他可测量因素更可靠地预测其成年后的收入、监禁率和向上流动的可能性。在全球范围内，差距更为悬殊：出生在挪威的孩子，预期寿命比出生在中非共和国的孩子长约30年，接受的教育质量相当于额外14年的学校教育。地址不是人本身——但它是塑造这个人的脚手架。" },
    { en: "Geography operates through three interlocking channels. The first is infrastructure: access to clean water, reliable electricity, paved roads, hospitals, and broadband is not evenly distributed. A child who grows up without consistent electricity cannot study after dark; one who faces a daily two-hour walk to school loses years of effective learning time. The second channel is institutions: the quality of courts, property rights, healthcare systems, and civil services shapes what risks people can afford to take and how quickly failure can be recovered from. The third is culture-of-place: local norms around education, marriage, gender roles, and civic participation create opportunity gradients even within the same country.", zh: "地理通过三个相互咬合的渠道发挥作用。第一是基础设施：获得清洁饮水、稳定电力、硬化道路、医院和宽带网络的机会分布不均。一个没有稳定电力的孩子无法在天黑后学习；每天需要步行两小时上学的孩子，则在有效学习时间上损失了数年。第二是制度：法院质量、产权保障、医疗体系和公共服务的水平，塑造着人们能承担何种风险以及从失败中恢复的速度。第三是地方文化：围绕教育、婚姻、性别角色和公民参与的地方规范，即便在同一国家内部也造就了机会梯度。" },
    { en: "The comparison is not merely between rich and poor nations. Within countries, urban–rural divides can be as consequential as international borders. A child born in Shanghai and one born in a remote Yunnan village share a passport but inhabit dramatically different opportunity landscapes: different school funding per pupil, different proximity to universities, different job markets within cycling distance. The East-Asian metropolis archetype — dense, connected, with fierce educational competition and high public investment — consistently produces human capital at rates that puzzle economists accustomed to thinking of education as purely a function of wealth.", zh: "这种比较并不仅仅存在于富国与穷国之间。在国家内部，城乡差距有时与国际边界同样深刻。出生在上海的孩子与出生在云南偏远山村的孩子持有同一本护照，却生活在截然不同的机会图景中：不同的生均教育经费、不同的大学可及性、不同的骑车可达就业市场。东亚大都市原型——人口密集、联通高效、教育竞争激烈、公共投入充足——持续以令习惯于将教育纯粹视为财富函数的经济学家困惑的速率生产人力资本。" },
    { en: "Climate and ecology add another layer. Development economists including Jeffrey Sachs have documented robust correlations between tropical geography and lower long-run economic growth — a relationship mediated by disease burden (malaria alone costs sub-Saharan Africa an estimated 1.3 percent of GDP annually), agricultural productivity, and historical colonial patterns that were themselves shaped by geography. These are structural forces, not judgments on populations: the same people, transplanted to different geography, exhibit markedly different outcomes within a generation, as diaspora studies confirm.", zh: "气候与生态又增添了另一个维度。包括杰弗里·萨克斯在内的发展经济学家记录了热带地理与较低长期经济增长之间稳健的相关性——这一关系通过疾病负担（仅疟疾一项每年就让撒哈拉以南非洲损失估计1.3%的GDP）、农业生产率以及本身由地理塑造的历史殖民模式来传导。这些是结构性力量，而非对人口的价值判断：同样的人群，迁移到不同的地理环境中，在一代人之内便呈现出截然不同的结果，海外侨民研究证实了这一点。" },
    { en: "Geography is not destiny — but it sets the betting odds before the race begins. Policy can shift those odds dramatically: South Korea in 1950 had lower per-capita income than Ghana, yet four decades of targeted investment in education, infrastructure, and institutions vaulted it to OECD membership. China's coastal special economic zones lifted hundreds of millions out of poverty by selectively connecting geography to global markets. These examples show that the geography factory's output is a function of both natural endowment and deliberate social engineering — and that the engineering part is the one humanity can actually control.", zh: "地理不是命运——但它在赛跑开始前就已设定了赔率。政策能够显著改变这些赔率：1950年的韩国人均收入低于加纳，然而四十年来对教育、基础设施和制度的定向投资，使其跃升为经合组织成员国。中国的沿海经济特区通过选择性地将特定地理区域与全球市场相连，使数亿人口脱离贫困。这些案例表明，地理工厂的产出是自然禀赋与有意识社会工程的共同函数——而工程那部分，才是人类真正能够掌控的。" }
  ],
  cards: [
    { icon: "🏥", title: { en: "Life Expectancy at Birth", zh: "出生时预期寿命" }, body: { en: "A child born in Japan (84 years) will statistically outlive one born in Sierra Leone (54 years) by three decades. These gaps reflect healthcare access, sanitation, nutrition, and conflict exposure — all geographically concentrated. Life expectancy is the single number that most compresses geography's power over a body.", zh: "出生在日本的孩子（84岁）在统计上将比出生在塞拉利昂的孩子（54岁）多活三十年。这些差距反映了医疗可及性、卫生条件、营养状况和冲突暴露风险——这些因素都高度集中于特定地理区域。预期寿命是最能压缩地理对身体影响力的单一数字。" } },
    { icon: "📚", title: { en: "Years & Quality of Schooling", zh: "受教育年限与质量" }, body: { en: "PISA scores reveal a 300-point gap between the highest- and lowest-performing countries — equivalent to roughly seven years of learning. Geography shapes not just how many years a child spends in school, but what happens inside the classroom: teacher quality, curriculum rigor, and whether school feels safe are all functions of where you were born.", zh: "PISA分数揭示了表现最佳与最差国家之间约300分的差距——相当于大约七年的学习量。地理不仅塑造孩子在校的年数，也塑造课堂内部发生的一切：教师质量、课程严格程度，以及学校是否令人感到安全，都是出生地的函数。" } },
    { icon: "💰", title: { en: "Income & Economic Mobility", zh: "收入与经济流动性" }, body: { en: "A software engineer writing identical code earns 8× more in San Francisco than in Lagos — not because of talent differences but because of local market prices, institutional trust, and proximity to capital. Intergenerational income mobility (the chance a poor child becomes a rich adult) varies from around 0.8 percent in Denmark to 11.5 percent in Brazil, measured by the intergenerational earnings elasticity.", zh: "一名编写相同代码的软件工程师在旧金山的收入是拉各斯的8倍——不是因为才能差异，而是因为本地市场价格、制度信任和资本的可及性。代际收入流动性（贫困儿童成为富裕成年人的机会）差异极大，以代际收入弹性衡量，丹麦约为0.8%，巴西约为11.5%。" } },
    { icon: "🚰", title: { en: "Infrastructure & Basic Services", zh: "基础设施与基本服务" }, body: { en: "Two billion people still lack access to safe drinking water; 759 million have no electricity at home. These are not abstract statistics — they are daily constraints on study time, health, and economic participation. Electrification alone, studies show, increases female secondary school enrollment by 5–10 percentage points in low-income settings.", zh: "全球仍有20亿人无法获得安全饮用水；7.59亿人家中没有电力。这些不是抽象的统计数字——它们是对学习时间、健康状况和经济参与的日常约束。研究表明，仅电气化一项，在低收入地区就能使女性初中入学率提高5至10个百分点。" } },
    { icon: "🌡️", title: { en: "Climate & Disease Environment", zh: "气候与疾病环境" }, body: { en: "Children raised in high-malaria-burden regions lose an average of 25 school days per year to illness; survivors of severe malaria face measurable long-term cognitive deficits. Climate also shapes nutrition via agricultural yields: a one-degree-Celsius rise in growing-season temperature reduces cereal yields by roughly 5 percent, a headwind that disproportionately strikes tropical low-income countries.", zh: "在高疟疾负担地区成长的儿童，平均每年因病损失25天上学时间；严重疟疾的幸存者面临可测量的长期认知损伤。气候还通过农业产量影响营养：生长季气温每升高一摄氏度，谷物产量下降约5%，这一逆风不成比例地冲击热带低收入国家。" } },
    { icon: "🏙️", title: { en: "Urban vs. Rural Gradient", zh: "城乡梯度" }, body: { en: "Globally, urban children are 50 percent more likely to complete secondary school than rural peers, even controlling for family income. Cities concentrate teachers, clinics, networks, and ideas in a way that geography-of-density makes self-reinforcing. The fastest human development gains in history have coincided with urbanization waves — geography reshaping itself.", zh: "在全球范围内，即便控制家庭收入，城市儿童完成中学教育的可能性比农村同龄人高50%。城市以一种人口密度地理学使其自我强化的方式，集中了教师、诊所、人际网络和思想。历史上最快速的人类发展成就都伴随着城镇化浪潮——地理在重塑自身。" } }
  ],
  questions: [
    { q: { en: "Does geography trap people, or can individual effort overcome it?", zh: "地理会困住人吗，还是个人努力可以克服它？" }, a: { en: "Individual effort matters within the range geography allows — but the range itself varies enormously. A brilliant, hardworking child born in a conflict zone with no functioning schools faces structural barriers that effort alone cannot dissolve. The evidence suggests geography sets the floor and ceiling; individual agency operates between them. Policy can raise the floor.", zh: "在地理所允许的范围内，个人努力确实重要——但这个范围本身差异极大。一个在没有正常运作学校的冲突地区出生的聪明、勤奋的孩子，面临着单靠努力无法消解的结构性障碍。证据表明，地理设定了地板和天花板；个人能动性在二者之间运作。政策可以抬高地板。" } },
    { q: { en: "Is the geography penalty shrinking with the internet?", zh: "随着互联网的普及，地理的惩罚在缩小吗？" }, a: { en: "For some things, yes: online courses, remote work, and digital access are genuinely compressing certain geographic gaps. But the largest drivers of life expectancy and mobility — healthcare systems, physical safety, nutrition — remain stubbornly local. Digital connectivity helps most when the physical infrastructure beneath it is already adequate.", zh: "就某些方面而言，是的：在线课程、远程工作和数字接入确实在压缩某些地理差距。但影响预期寿命和流动性的最大驱动因素——医疗体系、人身安全、营养——依然顽固地受制于本地条件。当数字连接所依托的实体基础设施已经足够充分时，它的帮助才最为显著。" } }
  ],
  viz: "comparison",
  vizTitle: { en: "How Birthplace Sets the Odds", zh: "出生地如何设定人生的赔率" },
  comparison: {
    aspect: { en: "How birthplace shapes life expectancy, schooling, income, and infrastructure access", zh: "出生地如何影响预期寿命、教育、收入与基础设施可及性" },
    dimensions: [
      { en: "Nordic Welfare State (e.g. Sweden)", zh: "北欧福利国家（如瑞典）" },
      { en: "East-Asian Metropolis (e.g. Tokyo / Seoul)", zh: "东亚大都市（如东京 / 首尔）" },
      { en: "Fast-Growing Emerging Economy (e.g. urban Brazil / Indonesia)", zh: "高速增长新兴经济体（如巴西 / 印尼城市）" },
      { en: "Low-Income Rural Region (e.g. rural sub-Saharan Africa)", zh: "低收入农村地区（如撒哈拉以南非洲农村）" }
    ],
    cells: [
      { en: "Life expectancy ~83 yrs; universal healthcare from birth; 16+ expected years of schooling; top-quartile PISA scores; GDP per capita ~$55 000; near-universal broadband; strong social safety net makes downside risks recoverable.", zh: "预期寿命约83岁；出生即享有全民医保；预期受教育年限16年以上；PISA成绩居全球前四分之一；人均GDP约5.5万美元；宽带几乎全覆盖；完善的社会安全网使风险可承受。" },
      { en: "Life expectancy ~84 yrs (Tokyo world-highest); ferocious educational competition from pre-school; 15–16 expected schooling years; PISA top-3; GDP per capita ~$35 000–$55 000; near-total connectivity; status anxiety high — mental health trade-off is documented.", zh: "预期寿命约84岁（东京全球最高）；从学前阶段起就有激烈的教育竞争；预期受教育年限15至16年；PISA排名前三；人均GDP约3.5万至5.5万美元；连接几乎全覆盖；社会地位焦虑较高——心理健康代价已有记录。" },
      { en: "Life expectancy ~73–76 yrs; schooling access improving but quality uneven; 9–12 expected years; PISA mid-table; GDP per capita ~$5 000–$15 000; urban broadband decent, rural patchy; high inequality within country means outcomes split sharply by neighborhood.", zh: "预期寿命约73至76岁；教育可及性改善但质量参差不齐；预期受教育年限9至12年；PISA成绩居中；人均GDP约5000至1.5万美元；城市宽带尚可，农村断点较多；国内高度不平等意味着结果因社区不同而急剧分化。" },
      { en: "Life expectancy ~55–63 yrs; school attendance disrupted by distance, cost, and household labor; 5–7 expected years; learning quality often low (teacher absenteeism, no books); GDP per capita ~$500–$2 000; electricity access under 30%; malaria, waterborne disease, and malnutrition compound one another.", zh: "预期寿命约55至63岁；因距离、费用和家庭劳动，上学出勤受到干扰；预期受教育年限5至7年；学习质量往往较低（教师缺勤、缺乏教科书）；人均GDP约500至2000美元；电力普及率低于30%；疟疾、水源性疾病与营养不良相互叠加。" }
    ]
  },
  accent: "#5fb0e6",
};
export default sec;
