import type { Section } from "@/lib/types";

const sec: Section = {
  id: "womb-factory",
  num: 3,
  kicker: { en: "Factory 03 · Gestation", zh: "工厂 03 · 孕育" },
  title: { en: "The Womb Factory", zh: "子宫工厂" },
  lead: { en: "Before a single breath, before any name or story, a human being is already being built — forty weeks of staggering biological engineering conducted in darkness, silence, and perfect urgency.", zh: "在第一次呼吸之前，在任何名字或故事出现之前，一个人类已经开始被建造——在黑暗、沉默与完美的紧迫中，四十周令人叹为观止的生物工程学正在进行。" },
  body: [
    { en: "The womb is the most productive factory in biology. In forty weeks it converts a single cell into a being of approximately 37 trillion cells, organized into more than 200 distinct tissue types, with a brain containing nearly 100 billion neurons, a heart pumping 35 liters of blood per hour, and a sensory apparatus already trained on the acoustic and chemical environment of the mother. No human engineer has come close to replicating even a small fraction of this process. What makes it more remarkable is that the instructions are distributed: no central coordinator watches over the whole. Each cell reads its local context — chemical gradients, mechanical signals, timing cues — and decides its own fate.", zh: "子宫是生物学中最富生产力的工厂。它在四十周内将单个细胞转化为一个约有37万亿个细胞的生命体，这些细胞组织成200多种不同的组织类型，拥有近1000亿个神经元的大脑、每小时泵送35升血液的心脏，以及已经在母亲的声学和化学环境中训练过的感觉系统。没有任何人类工程师能够复制这个过程的哪怕一小部分。更令人称奇的是，这些指令是分布式的：没有中央协调者监控整个过程。每个细胞读取其局部环境——化学梯度、机械信号、时序线索——并自行决定自己的命运。" },
    { en: "The prenatal period is also a period of profound sensitivity to the external world. The placenta, often described as a barrier, is more accurately a highly selective interface. Oxygen, glucose, amino acids, and essential fatty acids cross freely. So do alcohol, nicotine, many pharmaceutical drugs, and some environmental toxins. Maternal stress hormones — cortisol and adrenaline — cross in altered form and act on fetal stress-response systems, potentially calibrating the developing brain toward vigilance. There is now substantial evidence that maternal nutrition, infection, stress, and exposure to environmental chemicals during pregnancy influence offspring health, behavior, and even disease risk decades later. The womb is not a sealed chamber; it is a highly permeable interface between the developing child and the world.", zh: "产前阶段也是对外部世界高度敏感的时期。胎盘常被描述为一道屏障，但更准确地说，它是一个高度选择性的界面。氧气、葡萄糖、氨基酸和必需脂肪酸可以自由通过。酒精、尼古丁、许多药物和部分环境毒素也能通过。母体应激激素——皮质醇和肾上腺素——以改变的形式穿越并作用于胎儿的应激反应系统，可能将发育中的大脑校准为高度警觉状态。现有大量证据表明，孕期母亲的营养、感染、压力和环境化学物质暴露，会影响后代的健康、行为，甚至数十年后的疾病风险。子宫不是一个密封的腔室，而是发育中的孩子与世界之间高度渗透的界面。" },
    { en: "Neuroscience has revealed that the third trimester fetus is not simply waiting. By week 28, the brain is producing sleep-wake cycles and can respond differentially to familiar versus novel sounds. Repeated exposure to a story, a melody, or a language during late pregnancy measurably alters the newborn's neural response to that stimulus — a form of learning that precedes birth by months. The mother's voice, filtered through amniotic fluid and the body wall, reaches the fetal auditory system and is encoded with special neural weight: at birth, newborns prefer their mother's voice over any other, demonstrating that prenatal auditory experience shapes early attachment.", zh: "神经科学已经揭示，妊娠晚期的胎儿并非仅仅在等待。到第28周，大脑已经产生睡眠-觉醒周期，并能对熟悉与陌生的声音做出不同反应。在妊娠晚期反复接触一个故事、一段旋律或一种语言，会显著改变新生儿对该刺激的神经反应——这是一种在出生前数月就已开始的学习形式。母亲的声音，经过羊水和体壁的过滤，到达胎儿的听觉系统，并被赋予特殊的神经权重：出生时，新生儿更喜欢母亲的声音而非任何其他声音，证明了产前听觉体验塑造了早期依恋。" },
    { en: "Birth itself is an active physiological event, not merely an exit. The mechanical compression of the birth canal squeezes amniotic fluid from the lungs; a surge of fetal catecholamines prepares the cardiovascular system for independent circulation; the first breath triggers a dramatic restructuring of blood flow as the foramen ovale and ductus arteriosus close. Simultaneously, microbial colonization begins: the vaginal canal seeds the newborn's gut with Lactobacillus species, initiating the microbiome that will influence immune development for years. Babies born by Caesarean section receive a different microbial inoculation — from skin flora — with measurable differences in early immune and metabolic trajectories, though the long-term clinical significance is still under active study.", zh: "分娩本身是一个主动的生理事件，而不仅仅是一次退出。产道的机械挤压将羊水从肺部排出；胎儿儿茶酚胺的激增为独立循环做好了心血管准备；第一次呼吸引发了血流的剧烈重组，因为卵圆孔和动脉导管开始关闭。与此同时，微生物定植开始：阴道产道用乳酸杆菌属细菌为新生儿的肠道「播种」，启动将影响免疫发育数年的微生物组。剖宫产出生的婴儿接受的是不同的微生物接种——来自皮肤菌群——在早期免疫和代谢轨迹上有可测量的差异，尽管长期临床意义仍在积极研究中。" }
  ],
  cards: [
    { icon: "🔴", title: { en: "Week 1–2: Implantation", zh: "第1–2周：植入" }, body: { en: "The blastocyst burrows into the uterine lining, establishing blood supply. The outer cells become the placenta; the inner cell mass becomes the embryo. Human chorionic gonadotropin (hCG) signals the mother's body to maintain pregnancy.", zh: "囊胚钻入子宫内膜，建立血液供应。外层细胞发育为胎盘，内细胞团发育为胚胎。人绒毛膜促性腺激素（hCG）向母体发出信号，维持妊娠。" } },
    { icon: "🧫", title: { en: "Week 3–4: Neural Tube", zh: "第3–4周：神经管" }, body: { en: "The neural tube — future brain and spinal cord — folds and closes by day 28. Failure to close completely produces neural tube defects. Maternal folate is essential at this stage, which is why supplementation before conception matters.", zh: "神经管——未来的大脑和脊髓——在第28天前折叠并闭合。闭合不完全会导致神经管缺陷。母体叶酸在这个阶段至关重要，这就是为什么在受孕前补充叶酸如此重要。" } },
    { icon: "❤️", title: { en: "Week 6: First Heartbeat", zh: "第6周：第一次心跳" }, body: { en: "Electrical impulses begin in the primitive heart tube, which is still a simple loop rather than a four-chambered organ. By week 10 the four chambers are formed. The heart will beat approximately 3.5 billion times in a lifetime.", zh: "电脉冲在原始心管中开始产生，此时心脏仍是简单的环状结构，而非四腔器官。到第10周，四个心腔已形成。心脏在一生中将跳动约35亿次。" } },
    { icon: "👋", title: { en: "Week 10–16: Movement Begins", zh: "第10–16周：运动开始" }, body: { en: "Spontaneous limb movements appear by week 10, though the mother typically feels them only around weeks 16–20 (quickening). These movements are not random — they are essential for shaping joints and calibrating the proprioceptive nervous system.", zh: "自发的肢体运动在第10周出现，但母亲通常在第16至20周才能感觉到（胎动）。这些运动并非随机的——它们对于塑造关节形态和校准本体感觉神经系统至关重要。" } },
    { icon: "👁️", title: { en: "Week 22–26: Senses Online", zh: "第22–26周：感官上线" }, body: { en: "The fetus can respond to light (by turning away from a bright source placed at the mother's abdomen) and to sound by week 24. Taste receptors are functional by week 14 — flavor compounds from the mother's diet cross into amniotic fluid and influence postnatal food preferences.", zh: "到第24周，胎儿可以对光（通过背向放在母亲腹部的光源来响应）和声音做出反应。味觉受体在第14周就已功能性激活——来自母亲饮食的风味化合物穿过羊水，影响出生后的食物偏好。" } },
    { icon: "🧠", title: { en: "Week 24–38: Brain Wiring", zh: "第24–38周：大脑布线" }, body: { en: "The cerebral cortex expands dramatically in the third trimester, forming its characteristic folds (gyri and sulci). Synaptic connections are made and pruned at rates never again seen in life. REM sleep, which dominates the fetal sleep cycle, is thought to drive neural circuit consolidation.", zh: "在妊娠晚期，大脑皮层急剧扩张，形成其特征性的折叠（脑回和脑沟）。突触连接的形成和修剪速度是一生中最快的。REM睡眠——主导胎儿睡眠周期——被认为驱动着神经回路的巩固。" } },
    { icon: "🌊", title: { en: "The Placenta", zh: "胎盘" }, body: { en: "A temporary organ built partly from the embryo's own cells, the placenta transfers oxygen and nutrients, removes waste, produces hormones that maintain pregnancy, and selectively filters the environment. It is discarded at birth but is arguably the most important organ the body ever makes.", zh: "胎盘是一个部分由胚胎自身细胞构建的临时器官，它传输氧气和营养物质，清除废物，分泌维持妊娠的激素，并选择性地过滤环境。它在出生时被排出，但可以说是身体曾经制造的最重要的器官。" } },
    { icon: "🎵", title: { en: "Prenatal Learning", zh: "产前学习" }, body: { en: "Newborns show measurable preferences for sounds heard repeatedly in utero — their mother's voice, languages spoken nearby, melodies played during late pregnancy. This prenatal auditory learning is among the earliest evidence that the brain begins learning before birth.", zh: "新生儿对在子宫内反复听到的声音表现出可测量的偏好——他们母亲的声音、附近说的语言、妊娠晚期播放的旋律。这种产前听觉学习是大脑在出生前就开始学习的最早证据之一。" } }
  ],
  questions: [
    { q: { en: "Does what a mother eats, feels, or listens to actually affect the baby?", zh: "母亲的饮食、情绪或所听的音乐真的会影响婴儿吗？" }, a: { en: "Nutrition and stress: yes, substantially. Severe maternal stress during pregnancy is associated with elevated cortisol reaching the fetus, and epidemiological studies link maternal trauma (famine, disaster) with offspring health outcomes decades later. For music and specific cognitive stimulation, the evidence is far weaker — the fetus can learn to recognize sounds, but no study credibly shows that classical music produces smarter babies.", zh: "营养和压力：是的，影响显著。孕期母亲的严重压力与到达胎儿的皮质醇升高有关，流行病学研究将母亲经历的创伤（饥荒、灾难）与后代数十年后的健康结果相关联。对于音乐和特定认知刺激，证据要弱得多——胎儿能学会识别声音，但没有研究能可信地表明古典音乐能使婴儿更聪明。" } },
    { q: { en: "Is a premature baby at a permanent disadvantage?", zh: "早产儿会处于永久性的劣势吗？" }, a: { en: "Premature birth (before 37 weeks) cuts short critical periods of brain and lung development and carries real risks — with earlier birth carrying greater risk. However, outcomes vary enormously with gestational age at birth, quality of neonatal care, family support, and subsequent environment. Many children born prematurely, especially after 32 weeks, achieve typical developmental outcomes with appropriate support. Predisposition to difficulty is real; permanent disadvantage is not inevitable.", zh: "早产（37周之前）会缩短大脑和肺部发育的关键期，并带来真实风险——出生越早，风险越大。然而，结果因出生时的孕周、新生儿护理质量、家庭支持和后续环境而差异极大。许多早产儿，尤其是32周以后出生的，在适当支持下能够达到典型的发育结果。面临困难的遗传倾向是真实的，但永久性劣势并非不可避免。" } },
    { q: { en: "What is the most important thing for fetal brain development?", zh: "对胎儿大脑发育最重要的因素是什么？" }, a: { en: "Basic nutrition (especially omega-3 fatty acids, iodine, iron, and folate), absence of toxic exposures (alcohol has no known safe dose in pregnancy), and a low-stress maternal environment are the most robustly evidence-supported factors. Adequate sleep and prenatal care matter too. The third trimester — when synaptic proliferation peaks — is especially sensitive.", zh: "基本营养（尤其是omega-3脂肪酸、碘、铁和叶酸）、没有毒性暴露（酒精在孕期没有已知的安全剂量）以及低压力的母体环境，是证据最充分的因素。充足的睡眠和产前保健也很重要。妊娠晚期——突触增殖达到顶峰时——尤其敏感。" } }
  ],
  viz: "timeline",
  vizTitle: { en: "Forty Weeks: A Prenatal Timeline", zh: "四十周：产前时间线" },
  vizData: [
    { label: { en: "Week 1–2: Fertilization & Implantation", zh: "第1–2周：受精与植入" }, year: 1, group: "Foundation", note: { en: "Zygote forms, travels to the uterus, and implants as a blastocyst. hCG is secreted; pregnancy is established. All 46 chromosomes are in place within hours of fertilization.", zh: "受精卵形成，向子宫移行，以囊胚形式植入。hCG开始分泌，妊娠建立。受精后数小时内，46条染色体全部就位。" } },
    { label: { en: "Week 3: Neural Tube Forms", zh: "第3周：神经管形成" }, year: 3, group: "Foundation", note: { en: "The embryonic disc folds into three layers. The neural plate, precursor to brain and spinal cord, begins to roll into the neural tube. Folate deficiency at this stage sharply raises neural tube defect risk.", zh: "胚盘折叠成三层。神经板——大脑和脊髓的前身——开始卷成神经管。此阶段叶酸缺乏会大幅增加神经管缺陷风险。" } },
    { label: { en: "Week 4: Heart Begins Beating", zh: "第4周：心脏开始跳动" }, year: 4, group: "Organs", note: { en: "The primitive heart tube contracts spontaneously for the first time — a loop of tissue generating electrical impulses before it is even a recognizable heart. The embryo is about 4mm long.", zh: "原始心管第一次自发收缩——一圈组织在尚未成为可辨认的心脏之前便产生了电脉冲。此时胚胎约4毫米长。" } },
    { label: { en: "Week 6–8: Face & Limbs", zh: "第6–8周：面部与四肢" }, year: 6, group: "Organs", note: { en: "Eyes, ears, and nostrils emerge as indentations. Arm and leg buds appear, then fingers and toes by week 8. All major organ systems are present in rudimentary form by the end of the first trimester.", zh: "眼睛、耳朵和鼻孔作为凹陷出现。手臂和腿芽出现，到第8周出现手指和脚趾。到第一孕期结束时，所有主要器官系统已以雏形形式存在。" } },
    { label: { en: "Week 10: First Movements", zh: "第10周：第一次运动" }, year: 10, group: "Nervous System", note: { en: "Spontaneous, reflex movements of limbs begin. The fetus can hiccup, swallow, and make breathing movements. These motions are neurologically essential — they shape the developing musculoskeletal system.", zh: "四肢的自发反射运动开始。胎儿可以打嗝、吞咽和做呼吸动作。这些运动在神经学上至关重要——它们塑造发育中的肌肉骨骼系统。" } },
    { label: { en: "Week 14: Taste Receptors", zh: "第14周：味觉感受器" }, year: 14, group: "Senses", note: { en: "Taste buds are functional. The fetus swallows amniotic fluid continuously, and flavors from the mother's diet — garlic, vanilla, carrot — cross into the fluid and are detected. Postnatal food preferences are partially shaped here.", zh: "味蕾开始发挥功能。胎儿持续吞咽羊水，母亲饮食中的风味——大蒜、香草、胡萝卜——穿过进入羊水并被感知。出生后的食物偏好在此部分形成。" } },
    { label: { en: "Week 20: Hearing Develops", zh: "第20周：听觉发育" }, year: 20, group: "Senses", note: { en: "The cochlea is functional. The fetus can hear low-frequency sounds from outside the mother's body. The mother's heartbeat, voice, and gut sounds form a constant soundscape. Repeated sounds begin to be encoded with differential neural weight.", zh: "耳蜗开始发挥功能。胎儿能听到来自母体外的低频声音。母亲的心跳、声音和肠道声音构成恒定的声音景观。反复出现的声音开始被编码为差异化的神经权重。" } },
    { label: { en: "Week 24: Viability Threshold", zh: "第24周：存活阈值" }, year: 24, group: "Nervous System", note: { en: "With intensive neonatal care, some infants born at 24 weeks survive. The lungs are still critically immature — lacking surfactant — but the brain can sustain basic sensory and motor responses. This week marks the legal and medical viability threshold in many countries.", zh: "在重症新生儿护理下，一些在第24周出生的婴儿能够存活。肺部仍严重不成熟——缺乏表面活性物质——但大脑能维持基本的感觉和运动反应。这一周在许多国家标志着法律和医学上的存活阈值。" } },
    { label: { en: "Week 28: Sleep-Wake Cycles", zh: "第28周：睡眠-觉醒周期" }, year: 28, group: "Nervous System", note: { en: "The brain begins alternating between active (REM) and quiet sleep states. EEG recordings show burst-suppression patterns — the electrical signature of an immature but functional cortex. REM sleep is thought to consolidate early neural circuits.", zh: "大脑开始在活跃（REM）和安静睡眠状态之间交替。EEG记录显示爆发-抑制模式——不成熟但功能性皮层的电信号特征。REM睡眠被认为能巩固早期神经回路。" } },
    { label: { en: "Week 28–38: Cortical Folding", zh: "第28–38周：皮层折叠" }, year: 32, group: "Nervous System", note: { en: "The cerebral cortex, smooth at 28 weeks, develops its characteristic gyri and sulci as the surface area grows faster than the skull allows. Synaptic connections are made and pruned at rates never again approached after birth. This is the brain's greatest building phase.", zh: "在第28周时平滑的大脑皮层，随着表面积增长速度超过颅骨允许的范围，发展出其特征性的脑回和脑沟。突触连接的形成和修剪速度是出生后再也无法接近的。这是大脑最大的建设阶段。" } },
    { label: { en: "Week 36: Lungs Mature", zh: "第36周：肺部成熟" }, year: 36, group: "Organs", note: { en: "Surfactant production reaches levels sufficient for independent breathing. The fetus is “full-term early” and has a high chance of healthy birth. Fat deposits accumulate under the skin; body weight roughly doubles from week 32 to 40.", zh: "表面活性物质的产生达到足以独立呼吸的水平。胎儿进入「足月早期」，健康出生的可能性很高。脂肪沉积在皮肤下积累；从第32周到第40周，体重大约翻倍。" } },
    { label: { en: "Week 40: Birth", zh: "第40周：出生" }, year: 40, group: "Birth", note: { en: "Labor is triggered by a cascade of hormonal signals — fetal cortisol, oxytocin, prostaglandins. The birth canal's mechanical compression clears fluid from the lungs; the first breath restructures pulmonary circulation. Microbial colonization begins. A new human enters the world, already changed by it.", zh: "分娩由一系列激素信号触发——胎儿皮质醇、催产素、前列腺素。产道的机械压迫将液体从肺部清除；第一次呼吸重构了肺循环。微生物定植开始。一个新人类进入世界，已被世界改变。" } }
  ],
  quote: { text: { en: "“We begin to learn even before we are born.”", zh: "「我们在出生之前就已开始学习。」" }, attr: { en: "— Jacques Mehler, cognitive neuroscientist", zh: "— 雅克·梅勒，认知神经科学家" } },
  accent: "#ff7a92",
};

export default sec;
