import type { Section } from "@/lib/types";
const sec: Section = {
  id: "technology-factory",
  num: 10,
  kicker: { en: "Factory 10 · Technology", zh: "工厂 10 · 技术" },
  title: { en: "The Technology Factory", zh: "技术工厂" },
  lead: { en: "Every great technology is a rewrite of the human nervous system — electricity extended our muscles, the internet extended our memory, and AI is beginning to extend our judgment.", zh: "每一项伟大技术都是对人类神经系统的一次重写——电力延伸了肌肉，互联网延伸了记忆，人工智能正在开始延伸我们的判断力。" },
  body: [
    { en: "Technology does not merely change what we do; it changes who we are. When the electric grid lit up factories and homes in the 1880s, it dissolved the ancient tyranny of daylight. Night shifted from rest to possibility. Shift work, urban nightlife, and a new industrial rhythm reshaped the body clocks and social expectations of every person born into an electrified world.", zh: "技术不仅改变我们的行为，它改变我们是谁。1880年代电网点亮工厂与家园，彻底打破了昼夜的古老秩序。夜晚从休息时段变成可能性的延伸。轮班制、城市夜生活与新的工业节奏，重塑了每一个在电气化世界中出生的人的生物钟与社会期望。" },
    { en: "Radio and television — arriving in force by mid-20th century — did something subtler and more profound: they manufactured a shared reality for mass populations who had never met. A child in rural Mississippi and a child in suburban Chicago could watch the same cartoon, fear the same villains, and absorb the same consumer desires. Broadcast media was the first technology to homogenize culture at continental scale, and researchers have since documented its measurable effects on gender attitudes, political identity, and aspirations.", zh: "20世纪中叶普及的广播与电视，做到了更微妙也更深远的事情：它为素未谋面的大众制造了一个共享的现实。密西西比乡村的孩子与芝加哥郊区的孩子，可以看同一部卡通、惧怕同一个反派、汲取同一种消费欲望。广播媒体是第一种在大陆规模上均质化文化的技术，研究者此后记录了它对性别观念、政治身份和个人抱负的可量化影响。" },
    { en: "The personal computer of the 1980s relocated cognition. For the first time in history, a majority of knowledge workers began to think partially outside their skulls — drafting, revising, calculating, and storing in silicon. This externalization of working memory fundamentally altered how expertise was built: deep memorization mattered less; navigation, synthesis, and interface fluency mattered more. Entire new occupational categories emerged within a single generation.", zh: "1980年代的个人电脑将认知重新定位。历史上首次，大多数知识工作者开始将思维部分外包到颅骨之外——在硅片上起草、修改、计算和存储。工作记忆的这种外化，从根本上改变了专业知识的构建方式：深度记忆变得不那么重要，而导航、综合与界面流畅度变得更为关键。整整一代人内，全新的职业类别应运而生。" },
    { en: "The internet and the smartphone together compressed geography and time. By 1995, email and early web browsers began untethering information from physical location; by 2010, the smartphone ensured that untethering was total and permanent. Social psychologists now document that teenagers who came of age after 2012 — the first generation to spend adolescence with pocket supercomputers — show measurably different patterns of anxiety, social comparison, sleep disruption, and identity formation than every prior cohort. Technology shapes not just careers and habits but the architecture of the self.", zh: "互联网与智能手机共同压缩了地理与时间。1995年，电子邮件和早期网络浏览器开始让信息脱离物理位置的束缚；到2010年，智能手机使这种脱离彻底且永久。社会心理学家发现，2012年后进入青春期的青少年——第一代在口袋超级计算机陪伴下成长的人——在焦虑、社会比较、睡眠紊乱和身份建构方面，与所有前辈群体呈现出可量化的不同模式。技术塑造的不只是职业与习惯，而是自我的结构。" },
    { en: "AI, arriving at civilizational scale in 2023, poses the deepest rewrite yet. Prior technologies augmented specific human capacities; AI augments the capacity for augmentation itself — it learns, reasons, writes, codes, and advises. Economists debate whether this will be liberating or dislocating; the honest answer is both, unevenly distributed. What seems certain is that a person born today will construct their sense of expertise, creativity, and even companionship in relation to AI systems in ways that are simply unprecedented in any prior era of human history.", zh: "2023年，人工智能以文明规模到来，带来迄今最深刻的重写。此前的技术增强人类的特定能力；AI增强的是增强本身的能力——它学习、推理、写作、编程、提供建议。经济学家争论这将是解放还是错位；诚实的答案是两者皆有，且分配不均。可以确定的是，今天出生的人，将以前所未有的方式，在与AI系统的关系中建构自己对专业技能、创造力乃至陪伴的感知。" }
  ],
  cards: [
    { icon: "⚡", title: { en: "Electricity (1880s)", zh: "电力（1880年代）" }, body: { en: "Conquered night and powered industrial scale, resetting human rhythms, enabling shift work, and birthing the modern city. The first technology to make time itself a manufactured resource.", zh: "征服黑夜，驱动工业规模，重置人类节律，催生现代城市。它是第一种将时间本身变为可制造资源的技术。" } },
    { icon: "📻", title: { en: "Radio & Television (1950s)", zh: "广播与电视（1950年代）" }, body: { en: "Created the first mass shared reality — same news, same celebrities, same fears, across millions who never met. Documented effects on gender roles, political identity, and consumer aspiration.", zh: "创造了第一个大众共享现实——数百万素不相识的人，接收同样的新闻、偶像与恐惧。对性别角色、政治认同和消费渴望有记录在案的深远影响。" } },
    { icon: "💻", title: { en: "Personal Computer (1980s)", zh: "个人电脑（1980年代）" }, body: { en: "Moved cognition outside the skull. Drafting, calculating, and storing shifted to silicon, redefining expertise from memorization to navigation and synthesis.", zh: "将认知移至颅骨之外。起草、计算与存储转入硅片，将专业知识的核心从记忆重新定义为导航与综合。" } },
    { icon: "🌐", title: { en: "Internet (1995)", zh: "互联网（1995年）" }, body: { en: "Untethered information from geography. Overnight, a curious mind in a small town gained access to the same libraries, markets, and voices as any metropolis — a radical compression of opportunity.", zh: "让信息脱离地理束缚。一夜之间，小城镇中好奇的头脑，获得了与任何大都市相同的图书馆、市场和声音——一次对机会的根本性压缩。" } },
    { icon: "📱", title: { en: "Smartphone (2010)", zh: "智能手机（2010年）" }, body: { en: "Made the internet total and permanent — always on, always watching, always comparing. Research links post-2012 adolescent smartphone saturation to measurable shifts in anxiety, sleep, and identity formation.", zh: "使互联网变得全面且永久——始终在线、始终观察、始终比较。研究将2012年后青少年的智能手机饱和，与焦虑、睡眠和身份建构的可量化转变相关联。" } },
    { icon: "🤖", title: { en: "Artificial Intelligence (2023)", zh: "人工智能（2023年）" }, body: { en: "The first technology that augments augmentation itself — it learns, reasons, and advises at scale. Will reshape expertise, creativity, and labor in ways economists are still arguing about, with effects unevenly distributed.", zh: "第一种增强增强本身能力的技术——它在规模上学习、推理和建议。将以经济学家仍在争论的方式重塑专业技能、创造力与劳动，且影响分配不均。" } }
  ],
  questions: [
    { q: { en: "Does technology liberate us or enslave us?", zh: "技术解放了我们，还是奴役了我们？" }, a: { en: "Both, depending on the person and the era. Each major technology begins by expanding options and tends over time to create new dependencies and expectations. The smartphone offered freedom of access and delivered a surveillance economy. The honest framing is: liberation and enclosure arrive together, and how they distribute across populations is a political question as much as a technical one.", zh: "两者皆有，取决于个人与时代。每一项重大技术起初都在扩展选项，随后往往制造新的依赖与期望。智能手机提供了访问自由，却也带来了监控经济。诚实的表述是：解放与封锁同时到来，它们在人群中的分配方式，既是政治问题，也是技术问题。" } },
    { q: { en: "How does growing up with a technology change the person?", zh: "在某种技术中成长，如何改变一个人？" }, a: { en: "Profoundly and often invisibly. Children who grow up with a technology absorb its assumptions into their cognition before they can articulate them. Digital natives do not merely use the internet differently from digital immigrants — they think, remember, and relate differently. Each technological generation inherits a subtly different cognitive toolkit.", zh: "深刻而往往无形。在某种技术中成长的孩子，在能够明确表达之前，就已将其假设吸收进认知。数字原住民不仅以不同方式使用互联网——他们的思考、记忆和关系方式都不同。每一个技术世代继承了微妙不同的认知工具箱。" } }
  ],
  viz: "timeline",
  vizTitle: { en: "Technologies That Rewired Humanity", zh: "重塑人类的技术时间线" },
  vizData: [
    { label: { en: "Electricity", zh: "电力" }, group: "Infrastructure", note: { en: "Edison's grid (1882) conquered night, powered factories, and reset human circadian rhythms for the industrial age.", zh: "爱迪生电网（1882年）征服黑夜，驱动工厂，为工业时代重置人类昼夜节律。" }, year: 1880 },
    { label: { en: "Radio & Television", zh: "广播与电视" }, group: "Broadcast", note: { en: "Created a continental shared reality — same news, same fears, same desires — and documented effects on gender norms and political identity.", zh: "创造了大陆范围的共享现实——同样的新闻、恐惧与欲望——并记录了对性别规范和政治认同的影响。" }, year: 1950 },
    { label: { en: "Personal Computer", zh: "个人电脑" }, group: "Cognition", note: { en: "Moved thinking partly outside the skull — drafting, calculating, storing in silicon. Redefined expertise from memorization to navigation.", zh: "将思维部分移至颅骨之外——在硅片上起草、计算、存储。将专业知识从记忆重新定义为导航。" }, year: 1980 },
    { label: { en: "Internet", zh: "互联网" }, group: "Network", note: { en: "Untethered information from geography. A curious mind anywhere could access the same knowledge as any world-class library.", zh: "让信息脱离地理束缚。任何地方的好奇心，都能获得与世界顶级图书馆相同的知识。" }, year: 1995 },
    { label: { en: "Smartphone", zh: "智能手机" }, group: "Network", note: { en: "Made connectivity total and permanent. Linked to measurable shifts in adolescent anxiety, sleep, and identity formation post-2012.", zh: "使连接全面而永久。与2012年后青少年焦虑、睡眠和身份建构的可量化转变相关联。" }, year: 2010 },
    { label: { en: "Artificial Intelligence", zh: "人工智能" }, group: "Cognition", note: { en: "First technology to augment augmentation itself — learns, reasons, advises at scale. Reshaping expertise, creativity, and labor with effects still unfolding.", zh: "第一种增强增强本身能力的技术——在规模上学习、推理、建议。对专业技能、创造力和劳动的重塑仍在展开。" }, year: 2023 }
  ],
  accent: "#4fd6c4",
};
export default sec;
