import type { Section } from "@/lib/types";
const sec: Section = {
  id: "information-factory",
  num: 12,
  kicker: { en: "Factory 12 · Information", zh: "工厂 12 · 信息" },
  title: { en: "The Information Factory", zh: "信息工厂" },
  lead: { en: "You are, in a very precise sense, what you have read, watched, and been fed — the information diet a person consumes over a lifetime is one of the most powerful and least acknowledged sculptors of belief, identity, and judgment.", zh: "在非常精确的意义上，你就是你所读过、看过、被灌输过的东西——一个人一生所摄入的信息食谱，是信念、身份和判断力最强大却最少被承认的雕塑者之一。" },
  body: [
    { en: "Before the printing press, most humans received their worldview through a single channel: the oral tradition of their immediate community, mediated by elders, priests, and storytellers. Information was scarce, slow, and deeply local. The printing press broke this monopoly and, over two centuries, produced the Reformation, the Scientific Revolution, and the Enlightenment — not because the press was inherently liberating, but because pluralism of information sources, however chaotic, generates more perspectives than any single authority can suppress.", zh: "在印刷机出现之前，大多数人通过单一渠道接收世界观：由长者、神职人员和讲故事者调解的直接社区口头传统。信息稀缺、缓慢且深度地方化。印刷机打破了这种垄断，在两个世纪内催生了宗教改革、科学革命和启蒙运动——不是因为印刷机本质上是解放性的，而是因为信息来源的多元化，无论多么混乱，都能产生比任何单一权威能够压制的更多视角。" },
    { en: "Books remain the most powerful long-form information technology ever deployed. A single well-crafted book can transfer years of a thinker's most refined understanding into hours of a reader's experience. Research consistently finds that deep reading — sustained, uninterrupted engagement with a long text — builds the capacity for sustained attention, complex inference, and perspective-taking in ways that shorter formats do not replicate. The books a person encounters in childhood and early adulthood are disproportionately formative, because they arrive when the brain is most plastic and the worldview least formed.", zh: "书籍至今仍是有史以来部署的最强大的长篇信息技术。一本精心撰写的书，可以将一位思想家数年最精炼的理解，在数小时的阅读体验中传递给读者。研究一致发现，深度阅读——对长篇文本持续、不间断的投入——以短篇格式无法复制的方式，建构持续注意力、复杂推理和视角采纳的能力。一个人在童年和成年早期遇到的书籍，具有不成比例的塑造力，因为它们到来时，大脑最具可塑性，世界观最未成形。" },
    { en: "Mass media — broadcast television, newspapers, radio — operated as a narrowing funnel. A small number of editorial gatekeepers decided what millions would see, hear, and discuss. For much of the 20th century this created a kind of forced coherence: citizens of the same country shared baseline facts, even when they disputed interpretations. The dissolution of this shared factual layer — accelerated by cable television's fragmentation and then completed by the internet — has been one of the defining political events of the early 21st century.", zh: "大众媒体——广播电视、报纸、广播——作为一个收窄的漏斗运作。少数编辑把关人决定数百万人将看到、听到和讨论什么。在20世纪大部分时间里，这创造了一种强制性的一致性：同一国家的公民共享基本事实，即使他们对解释存在争议。这一共享事实层的瓦解——由有线电视的碎片化加速，再由互联网完成——是21世纪初最具决定性的政治事件之一。" },
    { en: "Social media and algorithmic feeds represent a qualitatively new information environment. For the first time in history, the primary editorial function — deciding what a person sees — has been delegated to an optimization process that maximizes engagement. Engagement, as every platform's internal research confirms, is not the same as truth, wisdom, or wellbeing. Content that provokes outrage, fear, or tribal solidarity is algorithmically amplified because it holds attention, regardless of its accuracy. Research links heavy social media use among adolescents to increased anxiety, political polarization, and susceptibility to misinformation — though causality is debated and individual effects vary.", zh: "社交媒体和算法推送代表了一种质上全新的信息环境。历史上首次，主要的编辑功能——决定一个人看到什么——被委托给一个最大化参与度的优化过程。正如每个平台的内部研究所证实的，参与度与真实性、智慧或幸福感并不相同。引发愤怒、恐惧或部落团结的内容，因其吸引注意力而被算法放大，无论其准确性如何。研究将青少年重度社交媒体使用与焦虑增加、政治极化和对虚假信息的易感性相关联——尽管因果关系尚存争议，个体效应也各有差异。" },
    { en: "AI-generated information is the newest and most uncertain frontier. Large language models can produce fluent, authoritative-sounding text on any topic in seconds, making the authorship and provenance of information increasingly opaque. The information environment of a child born today will contain, by the time they reach adulthood, an unknowable fraction of AI-generated content — persuasive, polished, and potentially detached from any ground truth. The ancient question of how to distinguish reliable knowledge from plausible noise has become more urgent than at any point since the printing press, and the cognitive tools required to navigate it — source evaluation, probabilistic reasoning, epistemic humility — are not instinctive. They must be taught.", zh: "AI生成的信息是最新也是最不确定的前沿。大型语言模型可以在数秒内对任何话题生成流畅、听起来权威的文本，使信息的作者身份和来源日益不透明。今天出生的孩子的信息环境，到他们成年时，将包含不可知比例的AI生成内容——具有说服力、精心打磨，且可能与任何基础事实脱钩。自印刷机出现以来，如何区分可靠知识与貌似合理的噪音，这一古老问题从未如此紧迫，而驾驭它所需的认知工具——来源评估、概率推理、认识论谦逊——并非本能。它们必须被教授。" }
  ],
  cards: [
    { icon: "📚", title: { en: "Books", zh: "书籍" }, body: { en: "The most powerful long-form information technology ever deployed. Deep reading builds sustained attention, complex inference, and perspective-taking. Books encountered in childhood and early adulthood are disproportionately formative — they arrive when the brain is most plastic.", zh: "有史以来部署的最强大长篇信息技术。深度阅读建构持续注意力、复杂推理和视角采纳能力。童年和成年早期遇到的书籍具有不成比例的塑造力——它们到来时大脑最具可塑性。" } },
    { icon: "📺", title: { en: "Mass Media", zh: "大众媒体" }, body: { en: "Broadcast television and newspapers operated as a narrowing funnel — few gatekeepers, millions of viewers. This forced a shared factual baseline for much of the 20th century. Its dissolution has been one of the defining political events of our era.", zh: "广播电视和报纸作为收窄的漏斗运作——少数把关人，数百万受众。这为20世纪大部分时间强制创造了共享事实基线。其瓦解已成为我们时代最具决定性的政治事件之一。" } },
    { icon: "📱", title: { en: "Social Media", zh: "社交媒体" }, body: { en: "For the first time, editorial curation was delegated to an engagement-maximization algorithm. Engagement ≠ truth. Outrage and fear are algorithmically amplified. Research links heavy adolescent use to increased anxiety and political polarization — causality debated, individual effects vary.", zh: "首次将编辑策展委托给参与度最大化算法。参与度≠真实性。愤怒与恐惧被算法放大。研究将青少年重度使用与焦虑增加和政治极化相关联——因果关系尚存争议，个体效应各异。" } },
    { icon: "🔮", title: { en: "Algorithms & Filter Bubbles", zh: "算法与过滤泡沫" }, body: { en: "Recommendation engines optimize for watch-time, not breadth. Over time, they converge on a narrow band of content that matches and reinforces existing preferences — narrowing the information diet without the user noticing.", zh: "推荐引擎为观看时长而非广度而优化。随着时间推移，它们收敛到一个与现有偏好相匹配并强化现有偏好的狭窄内容带——在用户不知不觉中收窄信息食谱。" } },
    { icon: "🤖", title: { en: "AI-Generated Content", zh: "AI生成内容" }, body: { en: "Large language models produce fluent, authoritative-sounding text at scale, making provenance increasingly opaque. A child born today will grow up in an information environment containing an unknowable fraction of AI-generated content — polished, persuasive, and potentially disconnected from ground truth.", zh: "大型语言模型大规模生成流畅、听起来权威的文本，使来源日益不透明。今天出生的孩子将在包含不可知比例AI生成内容的信息环境中成长——精心打磨、具有说服力，且可能与基础事实脱钩。" } },
    { icon: "🧠", title: { en: "Epistemic Literacy", zh: "认知素养" }, body: { en: "Source evaluation, probabilistic reasoning, and epistemic humility are not instinctive — they must be taught. The cognitive tools required to navigate a high-noise information environment are among the most consequential skills of the 21st century, and among the least consistently taught.", zh: "来源评估、概率推理和认识论谦逊并非本能——它们必须被教授。驾驭高噪音信息环境所需的认知工具，是21世纪最具决定性的技能之一，也是最缺乏系统教授的技能之一。" } },
    { icon: "🗞️", title: { en: "Information Diet", zh: "信息食谱" }, body: { en: "Just as a physical diet shapes the body, the information diet shapes cognition, beliefs, and identity. A diverse, high-quality information diet — spanning disciplines, geographies, and timeframes — is one of the most asymmetrically valuable habits a person can cultivate.", zh: "正如饮食塑造身体，信息食谱塑造认知、信念和身份。跨越学科、地理和时间框架的多样化、高质量信息食谱，是一个人可以培养的最具不对称价值的习惯之一。" } }
  ],
  questions: [
    { q: { en: "Does the medium shape the message — and the mind?", zh: "媒介塑造信息——以及心智——吗？" }, a: { en: "Marshall McLuhan argued yes, and decades of research support the intuition. Television rewards emotional immediacy; books reward patient reasoning; social media rewards brevity and provocation. Each medium does not just carry content — it trains cognitive habits. Heavy users of any medium gradually become better adapted to its particular demands, and less adapted to what it does not reward.", zh: "马歇尔·麦克卢汉认为是的，数十年的研究支持这一直觉。电视奖励情感即时性；书籍奖励耐心推理；社交媒体奖励简洁和刺激。每种媒介不仅承载内容——它训练认知习惯。任何媒介的重度用户，逐渐更好地适应其特定需求，而对它不奖励的东西则适应性降低。" } },
    { q: { en: "Can you escape your information bubble?", zh: "你能逃出自己的信息泡沫吗？" }, a: { en: "Deliberately, yes — but it requires active counter-programming. Algorithms will not do it for you; they are designed to serve comfort. Practices that help: reading books and long-form journalism from multiple political traditions, following people whose conclusions you distrust but whose reasoning you respect, and maintaining the habit of distinguishing 「I disagree with this」 from 「this is false.」 Exposure to high-quality disagreement is cognitively expensive and socially uncomfortable — which is precisely why it is valuable.", zh: "刻意为之，可以——但需要主动的反向编程。算法不会替你做这件事；它们被设计为服务于舒适感。有帮助的做法：阅读来自多种政治传统的书籍和长篇新闻，关注那些你不认同其结论但尊重其推理的人，并保持区分「我不同意这个」和「这是错误的」的习惯。接触高质量的分歧在认知上代价高昂，在社交上令人不适——这恰恰是它为何有价值的原因。" } }
  ],
  viz: "cards",
  accent: "#9b8cff",
};
export default sec;
