import type { Section } from "@/lib/types";
const sec: Section = {
  id: "social-factory",
  num: 11,
  kicker: { en: "Factory 11 · Social World", zh: "工厂 11 · 社会世界" },
  title: { en: "The Social Factory", zh: "社会工厂" },
  lead: { en: "No one is self-made — every human being is, in part, a distillation of the people who surrounded them, advised them, believed in them, or simply happened to mention the right opportunity at the right moment.", zh: "没有人是自我造就的——每一个人，在某种程度上，都是围绕在他们身边、指导他们、信任他们，或只是在恰当时机提到正确机遇的那些人的精华。" },
  body: [
    { en: "Humans are the most social species on Earth by a significant margin. Unlike other great apes, we cooperate with strangers, maintain relationships across decades, and build institutions that outlast any individual life. This social architecture is not a backdrop to human development — it is one of its primary engines. The quality, diversity, and reach of a person's social world predicts outcomes in health, wealth, creativity, and resilience with striking consistency across cultures.", zh: "人类是地球上社交性最强的物种，远超其他近亲。与其他类人猿不同，我们与陌生人合作，维系跨越数十年的关系，并建立超越任何个体生命的制度。这种社会结构不是人类发展的背景——它是其主要引擎之一。一个人社会世界的质量、多样性与广度，在跨文化研究中，以惊人的一致性预测着健康、财富、创造力和韧性方面的结果。" },
    { en: "The strongest predictor of longevity in the Harvard Study of Adult Development — which followed men for over 80 years — was not wealth, fame, or IQ, but the warmth of their close relationships. Strong friendships predict not just happiness but immune function, cardiovascular health, and recovery from illness. The mechanism appears to be stress buffering: knowing that trusted people are available reduces the physiological cost of threat, literally keeping cortisol lower and inflammation in check.", zh: "哈佛成人发展研究追踪男性超过80年，发现长寿的最强预测因素不是财富、名声或智商，而是亲密关系的温度。强健的友谊不仅预测幸福感，还预测免疫功能、心血管健康和疾病康复。其机制似乎是压力缓冲：知道有可信任的人在场，会降低面对威胁时的生理代价，字面意义上降低皮质醇水平并抑制炎症反应。" },
    { en: "Beyond close friends, sociologist Mark Granovetter's landmark research on 「the strength of weak ties」 revealed a counterintuitive truth: the acquaintances we barely know — former colleagues, neighbors we greet in passing, contacts from different industries — are often more valuable for opportunity than our close friends. Weak ties bridge different social clusters; strong ties tend to share the same information. When people find new jobs, discover innovations, or change careers, they disproportionately credit a casual acquaintance — someone on the periphery of their network.", zh: "在亲密朋友之外，社会学家马克·格兰诺维特关于「弱联系的力量」的开创性研究，揭示了一个反直觉的真相：我们几乎不认识的熟人——前同事、偶尔打招呼的邻居、来自不同行业的联系人——往往比亲密朋友更有机会价值。弱联系连接不同的社交群体；强联系则倾向于共享相同的信息。当人们找到新工作、发现创新或转换职业时，他们不成比例地将功劳归于一位泛泛之交——网络边缘的某个人。" },
    { en: "Mentors occupy a peculiar and powerful position in the social network: they are strong ties who nevertheless inhabit a different social stratum, providing both warmth and access. Research on career trajectories consistently shows that people with mentors advance faster, earn more, and report higher job satisfaction — not only because of the advice received, but because mentors open doors that the mentee could not have found alone. In many fields, the mentor relationship is the primary mechanism by which tacit knowledge — the unwritten rules, the judgment, the taste — passes between generations.", zh: "导师在社会网络中占据一种独特而强大的位置：他们是强联系，却同时处于不同的社会阶层，既提供温度，也提供通道。关于职业轨迹的研究一致表明，有导师的人晋升更快、收入更高、职业满意度更高——不仅因为获得了建议，还因为导师打开了被辅导者独自无法找到的门。在许多领域，导师关系是隐性知识——不成文的规则、判断力、品味——在代际间传递的主要机制。" },
    { en: "Social capital — the aggregate value stored in a person's network — is as real an asset as financial capital, and far less evenly distributed. Research by economist Raj Chetty and colleagues found that low-income children who grow up in areas with high cross-class social connectedness have dramatically better economic mobility outcomes than equally poor children in socially segregated areas. Who you know shapes what you can become, and the social geography of opportunity is one of the most consequential and least acknowledged inequalities in modern societies.", zh: "社会资本——一个人网络中储存的聚合价值——是与金融资本一样真实的资产，却分配远不均衡。经济学家拉杰·切蒂及其同事的研究发现，在跨阶层社会连接度高的地区成长的低收入儿童，其经济流动性结果远好于在社会隔离地区同等贫困的儿童。你认识谁，塑造了你能成为什么，机会的社会地理，是现代社会中最具决定性却最少被承认的不平等之一。" }
  ],
  cards: [
    { icon: "🤝", title: { en: "Close Friends", zh: "亲密朋友" }, body: { en: "The Harvard Study of Adult Development found warm close relationships to be the strongest single predictor of longevity and wellbeing — outperforming wealth, IQ, and fame. They buffer stress and keep inflammation low.", zh: "哈佛成人发展研究发现，温暖的亲密关系是长寿与幸福感的最强单一预测因素——超越财富、智商和名声。它们缓冲压力，抑制炎症。" } },
    { icon: "🌉", title: { en: "Weak Ties", zh: "弱联系" }, body: { en: "Granovetter's classic finding: casual acquaintances bridge different social clusters and are disproportionately responsible for new jobs, ideas, and opportunities. Peripheral contacts carry non-redundant information your close circle lacks.", zh: "格兰诺维特的经典发现：泛泛之交连接不同社交群体，是新工作、新想法和新机会的不成比例来源。边缘联系携带你亲密圈子所缺乏的非冗余信息。" } },
    { icon: "🏘️", title: { en: "Communities", zh: "社群" }, body: { en: "Religious congregations, professional associations, sports clubs, neighborhoods — communities provide identity, accountability, and a floor of belonging. They are the incubators of norms and the shock-absorbers of misfortune.", zh: "宗教会众、职业协会、体育俱乐部、社区——社群提供身份认同、责任感和归属感的底线。它们是规范的孵化器，也是不幸的减震器。" } },
    { icon: "🧭", title: { en: "Mentors", zh: "导师" }, body: { en: "Strong ties across social strata. Research consistently shows mentored individuals advance faster and earn more — not just from advice but because mentors transfer tacit knowledge and open otherwise invisible doors.", zh: "跨社会阶层的强联系。研究一致表明，受过辅导的人晋升更快、收入更高——不仅源于建议，还因为导师传递隐性知识，打开原本不可见的门。" } },
    { icon: "💎", title: { en: "Social Capital", zh: "社会资本" }, body: { en: "The aggregate value stored in your network. Chetty's research shows cross-class social connectedness predicts economic mobility more powerfully than local school quality or neighborhood safety. It is a form of wealth, and deeply unequal.", zh: "网络中储存的聚合价值。切蒂的研究表明，跨阶层社会连接度对经济流动性的预测力，强于当地学校质量或社区安全。它是一种财富，且极度不平等。" } },
    { icon: "📡", title: { en: "Network Diversity", zh: "网络多样性" }, body: { en: "Homogeneous networks feel comfortable but are cognitively stagnating. Research on innovation finds that people whose networks span industries, disciplines, and cultures generate more novel ideas — exposure to difference is the engine of creative recombination.", zh: "同质化网络令人舒适，却在认知上停滞。关于创新的研究发现，网络跨越行业、学科和文化的人，产生更多新颖想法——接触差异是创造性重组的引擎。" } }
  ],
  questions: [
    { q: { en: "Can you deliberately build better social capital?", zh: "你能刻意构建更好的社会资本吗？" }, a: { en: "Yes, with caveats. Research suggests that intentional community-building, maintaining weak ties, seeking mentors proactively, and diversifying one's network across industries all improve outcomes. But social capital is not purely a personal project — it is also a structural one. People born into socially rich environments start with an enormous head start, and closing that gap requires policy as much as individual effort.", zh: "可以，但有前提。研究表明，刻意建设社群、维系弱联系、主动寻求导师，以及跨行业多元化网络，都能改善结果。但社会资本不纯粹是个人项目——它也是结构性的。出生在社会资源丰富环境中的人，起点就具有巨大优势，弥合这一差距需要政策与个人努力的共同作用。" } },
    { q: { en: "Why do lonely people die younger?", zh: "为什么孤独的人死得更早？" }, a: { en: "Loneliness triggers a chronic low-grade stress response — the body interprets social isolation as physical danger, and keeps the immune and cardiovascular systems on alert. Over years, this sustained activation accelerates aging at the cellular level, raises blood pressure, and increases inflammatory markers. Epidemiologist John Cacioppo estimated the mortality risk of chronic loneliness as comparable to smoking 15 cigarettes a day.", zh: "孤独会触发慢性低度压力反应——身体将社会隔离解读为身体危险，并使免疫和心血管系统保持警戒状态。多年下来，这种持续激活在细胞层面加速衰老，升高血压，增加炎症标志物。流行病学家约翰·卡西奥波估计，长期孤独的死亡风险相当于每天吸15支烟。" } }
  ],
  viz: "constellation",
  vizTitle: { en: "The Social Universe — Who Shapes You", zh: "社会宇宙——谁塑造了你" },
  vizData: [
    { label: { en: "Close Friends", zh: "亲密朋友" }, group: "Strong Ties", note: { en: "Warmth, trust, and stress-buffering. The Harvard Study found them the top predictor of longevity.", zh: "温度、信任与压力缓冲。哈佛研究发现，它们是长寿的首要预测因素。" } },
    { label: { en: "Best Friend", zh: "挚友" }, group: "Strong Ties", note: { en: "A single high-quality close friendship in adolescence has been shown to predict lower rates of depression decades later.", zh: "青少年时期一段高质量的亲密友谊，被证明能预测数十年后更低的抑郁率。" } },
    { label: { en: "Romantic Partner", zh: "伴侣" }, group: "Strong Ties", note: { en: "Co-regulation of emotion and physiology — partners literally synchronize heart rates, sleep cycles, and stress responses over time.", zh: "情绪和生理的共同调节——伴侣随时间同步心率、睡眠周期和压力反应。" } },
    { label: { en: "Former Colleague", zh: "前同事" }, group: "Weak Ties", note: { en: "Granovetter's paradigm case: someone who knew you in a different context carries non-redundant information about opportunities you cannot see from inside your current circle.", zh: "格兰诺维特的典型案例：在不同背景下认识你的人，携带着你从当前圈子内部无法看到的非冗余机会信息。" } },
    { label: { en: "Cross-Industry Acquaintance", zh: "跨界熟人" }, group: "Weak Ties", note: { en: "Network diversity across sectors drives creative recombination — the biologist who knows a software engineer discovers patterns neither would find alone.", zh: "跨行业网络多样性驱动创造性重组——认识软件工程师的生物学家，发现了两人独自都无法找到的模式。" } },
    { label: { en: "Online Community", zh: "在线社群" }, group: "Communities", note: { en: "Digital communities can provide belonging and norms across geography — but research finds they supplement rather than replace in-person community for deep wellbeing.", zh: "数字社群可以跨越地理提供归属感和规范——但研究发现，对于深度幸福感，它们是补充而非替代线下社群。" } },
    { label: { en: "Religious / Civic Community", zh: "宗教/公民社群" }, group: "Communities", note: { en: "Regular in-person community — regardless of specific beliefs — is one of the strongest predictors of subjective wellbeing and resilience in adversity.", zh: "定期的线下社群——无论具体信仰如何——是主观幸福感和逆境韧性的最强预测因素之一。" } },
    { label: { en: "Professional Mentor", zh: "职业导师" }, group: "Mentors", note: { en: "A senior person in your field who transfers tacit knowledge — the unwritten rules, the judgment, the taste — that no textbook contains.", zh: "你领域内传授隐性知识的资深人士——那些没有任何教科书包含的不成文规则、判断力与品味。" } },
    { label: { en: "Life Mentor", zh: "人生导师" }, group: "Mentors", note: { en: "Someone who has seen more of life's terrain and can help you see your own situation from outside the urgency of the present moment.", zh: "一个见过更多人生地形的人，能帮你从当下紧迫性之外，看清自己的处境。" } },
    { label: { en: "Network Reach", zh: "网络广度" }, group: "Social Capital", note: { en: "The number and diversity of weak-tie clusters you can activate. Chetty's data shows this predicts economic mobility more than local school quality.", zh: "你可以激活的弱联系群体的数量和多样性。切蒂的数据显示，这对经济流动性的预测力超过当地学校质量。" } },
    { label: { en: "Cross-Class Connections", zh: "跨阶层连接" }, group: "Social Capital", note: { en: "Low-income children with high cross-class social exposure have dramatically better life outcomes — exposure to different strata is itself an engine of mobility.", zh: "具有高跨阶层社会接触的低收入儿童，人生结果显著更好——接触不同阶层本身就是流动的引擎。" } }
  ],
  accent: "#ff7a92",
};
export default sec;
