import type { Section } from "@/lib/types";
const sec: Section = {
  id: "success-factory",
  num: 18,
  kicker: { en: "Factory 18 · Extraordinary Outcomes", zh: "工厂 18 · 非凡成就" },
  title: { en: "The Success Factory", zh: "成功工厂" },
  lead: { en: "Every extraordinary outcome is a compound of things you were born with, things you built, things that were handed to you, things that connected you, and things that arrived at precisely the right moment — and the uncomfortable truth is that no one can say with confidence what the exact proportions were.", zh: "每一项非凡成就，都是你与生俱来之物、你后天构建之物、偶然获赠之物、关系赋予之物，以及在恰当时机降临之物的复合产物——令人不安的真相是，没有人能自信地说出这些成分的确切比例。" },
  body: [
    { en: "The study of extraordinary achievement is plagued by survivorship bias: we study those who succeeded and work backwards to find the causes, ignoring the vast population of equally talented, effortful, well-connected people who did not. This methodological problem means that most popular theories of success — whether emphasising talent, grit, or networks — are likely to overstate the factor they celebrate and understate luck and timing.", zh: "对非凡成就的研究深受幸存者偏差的困扰：我们研究那些成功者，然后倒推原因，却忽视了同样有才华、同样努力、关系同样良好却未能成功的庞大人群。这一方法论问题意味着，大多数关于成功的流行理论——无论是强调天赋、坚毅还是人际网络——都可能夸大了它们所推崇的因素，而低估了运气与时机的作用。" },
    { en: "Talent — raw ability in a domain — is real but routinely over-romanticised. The evidence from cognitive science and genetics shows that domain-relevant ability is partly heritable and partly environmentally amplified. Critically, ability exists on continuous distributions: there is no sharp line between “gifted” and “ordinary,” and the correlation between measured ability and real-world achievement, while positive, is far from deterministic. Many highly talented people never achieve recognition; many celebrated achievers scored modestly on early ability measures.", zh: "天赋——某一领域的原始能力——是真实存在的，但常被过度浪漫化。来自认知科学和遗传学的证据表明，与领域相关的能力部分由遗传决定，部分由环境放大。关键在于，能力存在于连续分布中：在“天才”与“普通人”之间并无明确分界，而测量能力与现实世界成就之间的相关性，虽然为正，却远非决定性的。许多极具天赋的人从未获得认可；许多备受赞誉的成就者在早期能力测量中的得分也相当普通。" },
    { en: "Effort — deliberate, sustained, high-quality practice — is the factor most within individual control and the one most robustly associated with skill acquisition. Anders Ericsson's research on deliberate practice shows that top performers in almost every field have accumulated thousands of hours of focused practice with feedback. Yet Ericsson himself was careful to note that deliberate practice explains variation in performance among motivated practitioners — it does not explain who enters the field, who has access to quality coaching, or who can afford the time.", zh: "努力——刻意的、持续的、高质量的练习——是个人最能掌控的因素，也是与技能习得最为稳健相关的因素。安德斯·艾利克森对刻意练习的研究表明，几乎每个领域的顶尖表现者都积累了数千小时有反馈的专注练习。然而艾利克森本人也谨慎指出，刻意练习解释的是有动力的从业者之间的表现差异——它并不能解释谁进入了这个领域、谁能获得优质指导，以及谁能负担得起这些时间成本。" },
    { en: "Opportunity — access to resources, institutions, mentors, and fertile environments — is perhaps the most unequally distributed ingredient in extraordinary achievement. Robert Frank's research documents how small initial advantages (a better school, a slightly older birth-month in age-grouped sports, a parent with industry connections) compound over time into vast differences in outcome. The Matthew Effect — “to him who has, more will be given” — is one of the most replicated findings in the sociology of achievement.", zh: "机遇——获得资源、机构、导师和肥沃环境的途径——或许是非凡成就中分布最不平等的成分。罗伯特·弗兰克的研究记录了微小的初始优势（更好的学校、在按年龄分组的体育运动中稍大的出生月份、在行业中有关系的父母）如何随时间复利叠加，最终演变为结果上的巨大差异。马太效应——“凡有的，还要加给他”——是成就社会学中被复现最多的发现之一。" },
    { en: "Timing and networks are often treated as separate from “real” achievement, but the evidence suggests otherwise. Mark Granovetter's weak ties research shows that novel opportunities — jobs, ideas, collaborators — flow more often through acquaintances than through close friends, because acquaintances occupy different social worlds. And timing is not merely luck: it is the intersection of a prepared person with a particular moment in a field's development. Bill Gates did not become Bill Gates because he was merely talented or merely determined; he also had rare early access to a computer terminal in 1968, at the exact moment when hands-on computing time was historically scarce and therefore most formative.", zh: "时机与人际网络常被视为独立于“真正”成就之外的因素，但证据并不支持这一看法。马克·格兰诺维特关于弱连接的研究表明，新奇的机会——工作、创意、合作者——更多通过熟人而非密友传递，因为熟人占据着不同的社会世界。而时机也不仅仅是运气：它是一个有所准备的人与某一领域发展特定时刻的交汇。比尔·盖茨之所以成为比尔·盖茨，不仅因为他有才华或有决心；他还在1968年罕见地获得了早期上机机会，恰在计算机上机时间在历史上极为稀缺因而最具塑造力的那个时刻。" }
  ],
  cards: [
    { icon: "💡", title: { en: "Talent — the raw substrate", zh: "天赋——原始底料" }, body: { en: "Domain ability is real and partly heritable — but it exists on a spectrum, not in discrete “gifted” categories. Most extraordinary achievers were not the most talented people in their early cohorts; they were talented enough AND found the right conditions to develop.", zh: "领域能力是真实存在的，且部分由遗传决定——但它存在于一个连续谱上，而非离散的“天才”类别中。大多数非凡成就者在早期并非所在群体中最有天赋的人；他们只是足够有天赋，同时又找到了适合发展的正确条件。" } },
    { icon: "🔨", title: { en: "Effort — the multiplier", zh: "努力——倍增器" }, body: { en: "Deliberate practice — focused, effortful, feedback-rich — is the best-documented lever for skill growth within a field. But effort does not create opportunity; it converts it. Access to quality coaching, financial stability, and time to practise are prerequisites that effort alone cannot supply.", zh: "刻意练习——专注的、付出努力的、富有反馈的——是在某一领域内促进技能成长的最有文献记录的手段。但努力不能创造机遇；它只能将机遇转化为成果。获得优质指导、财务稳定以及练习时间，是努力本身无法单独提供的先决条件。" } },
    { icon: "🚪", title: { en: "Opportunity — the door", zh: "机遇——那扇门" }, body: { en: "Early access to mentors, institutions, and fertile environments creates compounding advantages that are invisible to those inside them. Research consistently shows that structural opportunity — not character — is the primary predictor of who gets to compete at the highest levels at all.", zh: "早期获得导师、机构和肥沃环境的途径，会产生复利式的优势，而身处其中的人对此浑然不觉。研究始终表明，结构性机遇——而非个人品质——才是决定谁能在最高层次参与竞争的首要预测因子。" } },
    { icon: "🕸️", title: { en: "Networks — the transmission system", zh: "人际网络——传导系统" }, body: { en: "Opportunities and information travel through social networks. Weak ties — people you know but not well — are disproportionately valuable because they bridge otherwise disconnected clusters. Access to powerful networks is itself distributed unequally along lines of class, geography, and cultural capital.", zh: "机遇与信息通过社交网络传播。弱连接——你认识但不太熟悉的人——价值异乎寻常，因为它们在原本互不相连的群体之间搭建桥梁。而接触强大网络的机会本身，又沿着阶层、地域和文化资本的轨迹，呈现出不平等的分布。" } },
    { icon: "⏱️", title: { en: "Timing — the invisible variable", zh: "时机——那个看不见的变量" }, body: { en: "A person with identical talent and effort achieves radically different outcomes depending on when they enter a field. Early entrants in an expanding market capture disproportionate rewards; latecomers face crowded landscapes. Bill Gates, Steve Jobs, and Mark Zuckerberg were all born within a narrow window — 1953–1984 — that placed them at the frontier of the PC and internet revolutions at precisely the right developmental age.", zh: "拥有相同天赋和努力的人，仅因进入某一领域的时间不同，就会取得截然不同的结果。在一个扩张市场中的早期进入者获得了不成比例的回报；晚来者则面对已经拥挤的格局。比尔·盖茨、史蒂夫·乔布斯和马克·扎克伯格都出生在1953至1984年这个狭窄的时间窗口内——这使他们在恰到好处的发展年龄，站在了个人电脑与互联网革命的前沿。" } }
  ],
  questions: [
    { q: { en: "If success depends so much on luck, does personal effort still matter?", zh: "如果成功如此依赖运气，个人努力还重要吗？" }, a: { en: "Yes — but as a necessary, not sufficient, condition. Effort determines how well you use the opportunities that arrive. The problem is that we routinely confuse “necessary for success” with “sufficient for success,” which leads us to blame failure on lack of effort while ignoring structural disadvantages. Both things are true simultaneously: effort matters and structural luck matters more than most success narratives admit.", zh: "重要——但它是必要条件，而非充分条件。努力决定了你能在多大程度上利用到来的机遇。问题在于，我们习惯性地将“成功的必要条件”与“成功的充分条件”相混淆，这导致我们将失败归咎于努力不足，而忽视了结构性不利因素。两件事同时为真：努力很重要，而结构性运气比大多数成功叙事所承认的更为重要。" } },
    { q: { en: "Can extraordinary achievement be taught or engineered?", zh: "非凡成就可以被教授或刻意设计出来吗？" }, a: { en: "Partially. Institutions can improve the probability of excellent outcomes by broadening access, identifying talent earlier and in more forms, providing quality coaching and mentorship, and reducing the waste of potential caused by inequality. But no programme can guarantee exceptional outcomes, because the intersection of preparation with the right moment in a field's development remains partly stochastic.", zh: "在一定程度上可以。机构可以通过拓宽准入渠道、更早且以更多形式识别天赋、提供高质量的指导和导师制，以及减少不平等造成的潜力浪费，来提高产出卓越成果的概率。但没有任何项目能保证产生卓越成果，因为准备充分的人与某一领域发展特定时刻的交汇，在一定程度上仍是随机的。" } }
  ],
  viz: "comparison",
  vizTitle: { en: "What Each Factor Contributes — and Where It Falls Short", zh: "每种因素的贡献与局限" },
  comparison: {
    aspect: { en: "Contribution to extraordinary outcomes — and its limits", zh: "对非凡成就的贡献及其局限" },
    dimensions: [
      { en: "Talent", zh: "天赋" },
      { en: "Effort", zh: "努力" },
      { en: "Opportunity", zh: "机遇" },
      { en: "Networks", zh: "人际网络" },
      { en: "Timing", zh: "时机" }
    ],
    cells: [
      { en: "Provides domain-relevant processing speed and pattern recognition. Sets a ceiling above which it is hard to push without the other factors — but the ceiling is almost never the binding constraint. Most talented people never reach their potential; most recognised achievers were not the most talented in their early cohort.", zh: "提供与领域相关的信息处理速度和模式识别能力。设定了一个没有其他因素配合就难以突破的上限——但这个上限几乎从来不是真正的制约因素。大多数有天赋的人从未发挥出全部潜力；大多数备受认可的成就者在早期并非所在群体中最有天赋的人。" },
      { en: "Converts latent ability into demonstrated skill through deliberate practice with feedback. The most individual-controllable factor, and robustly linked to expertise within a domain. Limit: effort cannot substitute for access — you cannot practise what you cannot afford to reach, and quality coaching is not equally available.", zh: "通过有反馈的刻意练习，将潜在能力转化为可展示的技能。是个人最能掌控的因素，与某一领域内的专业技能有稳健的关联。局限：努力无法替代准入机会——你无法练习你负担不起接触的事物，而高质量的指导也并非人人可及。" },
      { en: "Provides the environments, mentors, institutions, and economic security in which talent can develop. Research shows early structural advantages compound dramatically over time (Matthew Effect). Limit: opportunity is the most unequally distributed factor — and the one least discussed in popular success narratives, because those who benefited from it rarely noticed it.", zh: "提供天赋得以发展所需的环境、导师、机构和经济保障。研究表明，早期结构性优势会随时间显著复利积累（马太效应）。局限：机遇是分布最不平等的因素——也是在流行成功叙事中被讨论最少的因素，因为从中受益者往往浑然不觉。" },
      { en: "Channels information about opportunities (job openings, collaborators, funding, ideas) through social ties. Weak ties are especially valuable because they bridge different social worlds. Limit: network quality is itself a product of prior privilege — knowing the right people requires already being near them, geographically, institutionally, and socially.", zh: "通过社会关系传递关于机遇的信息（职位空缺、合作者、资金、创意）。弱连接尤其珍贵，因为它们在不同的社会世界之间搭建桥梁。局限：人际网络的质量本身就是先前特权的产物——认识对的人，需要已经在地理、机构和社会层面上靠近他们。" },
      { en: "Determines whether preparation meets expanding demand. Entering an emerging field before competition arrives yields compounding first-mover advantages. Limit: timing is largely beyond individual control — you cannot choose the year you are born or which industries will boom during your peak productive years. Awareness of timing can, at the margin, inform strategic choices about which fields to enter.", zh: "决定准备是否恰好遇上扩张中的需求。在竞争到来之前进入一个新兴领域，会产生复利式的先发优势。局限：时机在很大程度上超出个人控制——你无法选择出生年份，也无法选择哪些行业会在你最高产的年份蓬勃发展。对时机的认识，在边际上可以为进入哪些领域的战略选择提供参考。" }
    ]
  },
  quote: { text: { en: "“Success is a lousy teacher. It seduces smart people into thinking they can’t lose.”", zh: "「成功是一位糟糕的老师。它诱使聪明人以为自己永远不会失败。」" }, attr: { en: "— Bill Gates", zh: "— 比尔·盖茨" } },
  accent: "#e8b34a",
};
export default sec;
