import type { Section } from "@/lib/types";
const sec: Section = {
  id: "brain-factory",
  num: 16,
  kicker: { en: "Factory 16 · Neural Architecture", zh: "工厂 16 · 神经架构" },
  title: { en: "The Brain Factory", zh: "大脑工厂" },
  lead: { en: "You did not choose your brain — yet every choice you make is authored by it: a 1.4-kilogram electrochemical machine that rewires itself in response to every experience, every relationship, every habit you build or break.", zh: "你从未选择过自己的大脑——然而你所做的每一个选择，都由它主导。这台重约1.4公斤的电化学机器，会因每一次经历、每一段关系、每一个习惯的养成或打破，而不断重塑自身。" },
  body: [
    { en: "The brain is not a single organ but a federation of specialised systems, each shaped over hundreds of millions of years of evolution, each contributing a distinct layer to the experience of being human. Modern neuroscience no longer speaks of a simple triune brain, but the metaphor survives because the architecture is genuinely hierarchical: ancient circuits handle survival and emotion; newer regions layer planning, language, and self-regulation on top.", zh: "大脑并非一个单一器官，而是数亿年演化塑造的专业化系统的联合体，每个系统都为人类的存在体验贡献着独特的层次。现代神经科学已不再使用简单的“三位一体大脑”模型，但这一比喻仍然流传，因为其架构确实是层级化的：古老的神经回路负责生存与情绪，而更新的区域则在其上叠加了规划、语言与自我调节的能力。" },
    { en: "Memory is not a recording but a reconstruction. Every time the hippocampus retrieves a memory it briefly makes it labile — open to revision — before re-consolidating it. This means memories are narrative constructs, coloured by mood, expectation, and subsequent experience. The same event is literally remembered differently by different people, and differently by the same person over time.", zh: "记忆并非录像，而是一种重构。每当海马体提取一段记忆时，这段记忆会短暂地变得“不稳定”——对修改开放——然后才重新固化。这意味着记忆是叙事性的建构，受情绪、预期和后续经历的染色。同一件事，在不同人眼中的记忆截然不同，同一个人在不同时间的记忆也会有所差异。" },
    { en: "The reward system — centred on dopamine pathways running from the ventral tegmental area to the nucleus accumbens — does not fire in response to pleasure itself but in response to the prediction of reward. It encodes expectation, surprise, and disappointment. This means the brain is fundamentally a prediction machine, and motivation is less about what feels good now than about what the system predicts will feel good next.", zh: "奖励系统——以从腹侧被盖区延伸至伏隔核的多巴胺通路为核心——并非对快感本身作出反应，而是对奖励的预期作出反应。它编码的是期望、惊喜与失望。这意味着大脑从根本上是一台预测机器，动力的来源与其说是当下的感受，不如说是系统对下一刻的预期。" },
    { en: "Neuroplasticity — the brain's capacity to reorganise its synaptic connections in response to experience — is not a childhood privilege. Adult brains continue to prune weak connections and strengthen active ones throughout life, though the rate of change slows with age. Deliberate practice, novel environments, sleep, and aerobic exercise are among the best-documented levers for sustaining plasticity in the adult brain.", zh: "神经可塑性——大脑根据经验重组突触连接的能力——并非儿童的专利。成人大脑在整个生命历程中持续修剪弱连接、强化活跃连接，尽管变化速率随年龄增长而减缓。刻意练习、新奇环境、睡眠以及有氧运动，是目前有充分文献记录的、维持成人大脑可塑性的最佳手段。" },
    { en: "The prefrontal cortex — last to mature, not fully developed until the mid-twenties — is the seat of executive function: planning, impulse control, weighing long-term consequences. Its late development explains much about adolescent risk-taking, but also why early environments matter so acutely: the pre-frontal cortex is still forming when the stakes are highest.", zh: "前额叶皮层——成熟最晚，直到二十五岁左右才完全发育——是执行功能的核心：规划、冲动控制以及权衡长远后果。其发育滞后解释了青少年冒险行为的许多成因，也说明了为何早期环境如此关键：前额叶皮层仍在成型之际，正是风险最高之时。" }
  ],
  cards: [
    { icon: "🐎", title: { en: "Hippocampus & Memory", zh: "海马体与记忆" }, body: { en: "The hippocampus converts short-term experience into long-term memory and is essential for spatial navigation. Chronic stress and cortisol shrink hippocampal volume; enriched environments and learning can grow it back.", zh: "海马体将短期经历转化为长期记忆，是空间导航的关键结构。长期压力和皮质醇会使海马体体积缩小；而丰富的环境刺激与持续学习则能促使其恢复。" } },
    { icon: "🔥", title: { en: "Amygdala & Emotion", zh: "杏仁核与情绪" }, body: { en: "The amygdala flags emotional salience — especially threat. It can trigger fear responses faster than conscious thought, and its memories are vivid and persistent. Emotion is not the enemy of reason; it is its ancient partner.", zh: "杏仁核标记情绪显著性——尤其是威胁信号。它能在意识察觉之前触发恐惧反应，其留存的记忆既生动又持久。情绪并非理性的敌人，而是其古老的伙伴。" } },
    { icon: "⚡", title: { en: "Dopamine & Reward", zh: "多巴胺与奖励" }, body: { en: "Dopamine signals prediction error — the gap between expected and actual reward. It drives curiosity, motivation, and habit formation. Social media and gambling exploit this system by engineering unpredictable reward schedules.", zh: "多巴胺传递的是预测误差信号——即预期奖励与实际奖励之间的差距。它驱动好奇心、动力与习惯的形成。社交媒体和赌博正是通过设计不可预测的奖励机制来操控这一系统。" } },
    { icon: "🧭", title: { en: "Prefrontal Cortex & Control", zh: "前额叶皮层与控制" }, body: { en: "The prefrontal cortex enables planning, self-regulation, and delayed gratification. It matures last — completing development around age 25 — which is why adolescence is both a period of heightened creativity and heightened risk.", zh: "前额叶皮层使规划、自我调节与延迟满足成为可能。它是大脑中最晚成熟的区域——约在25岁完成发育——这也是青少年时期既充满创造力、又充满风险的原因所在。" } },
    { icon: "🔄", title: { en: "Basal Ganglia & Habit", zh: "基底神经节与习惯" }, body: { en: "The basal ganglia automate repeated behaviour into habits, freeing conscious attention for new challenges. Once a habit loop (cue→routine→reward) is encoded, it is virtually permanent — which is why habits must be replaced, not simply erased.", zh: "基底神经节将重复行为自动化为习惯，从而释放意识注意力去应对新挑战。一旦习惯回路（提示→常规→奖励）被编码，便几乎永久留存——这就是为什么习惯必须被替换，而非简单抹除。" } },
    { icon: "🌱", title: { en: "Neuroplasticity", zh: "神经可塑性" }, body: { en: "The brain physically remodels itself in response to experience: synapses strengthen with use and prune with neglect. Sleep is when consolidation happens. The implication: what you repeatedly attend to, you literally become.", zh: "大脑会根据经历在生理层面重塑自身：突触因使用而强化，因忽视而修剪。睡眠是记忆巩固发生的时刻。这意味着：你反复关注什么，你就会从字面意义上成为什么。" } }
  ],
  questions: [
    { q: { en: "Can adults really change their brains through deliberate practice?", zh: "成年人真的可以通过刻意练习改变大脑吗？" }, a: { en: "Yes — within limits. Studies of London taxi drivers show enlarged hippocampi from spatial learning; musicians show expanded motor cortex representations. The rate of change slows with age, but plasticity persists throughout life. Consistent practice, sleep, and aerobic exercise are the best-documented levers.", zh: "是的——但有其限度。对伦敦出租车司机的研究显示，空间学习使其海马体体积扩大；音乐家的运动皮层表征区域也有所扩展。变化速率随年龄增长而减缓，但可塑性在整个生命历程中持续存在。刻意练习、睡眠和有氧运动是目前文献记录最充分的有效手段。" } },
    { q: { en: "Is the brain more nature or nurture?", zh: "大脑更多由先天决定，还是由后天塑造？" }, a: { en: "Neither dominates — the question is outdated. Genes set structural parameters and predispositions; experience sculpts which circuits activate and how strongly. Early adversity can alter gene expression in brain circuits for decades. The brain is the organ through which nature and nurture are indistinguishable.", zh: "两者都不占主导——这个问题本身已经过时。基因设定结构参数和倾向性；经历则塑造哪些回路被激活以及激活的强度。早期逆境可在数十年间改变脑回路中的基因表达。大脑正是那个让先天与后天无法区分的器官。" } }
  ],
  viz: "constellation",
  vizTitle: { en: "Brain Systems Constellation", zh: "大脑系统星图" },
  vizData: [
    { label: { en: "Hippocampus", zh: "海马体" }, group: "Systems", note: { en: "Memory formation and spatial navigation; shrinks under chronic stress.", zh: "记忆形成与空间导航；在长期压力下体积缩小。" } },
    { label: { en: "Amygdala", zh: "杏仁核" }, group: "Systems", note: { en: "Emotional tagging, especially threat detection; triggers fear before conscious awareness.", zh: "情绪标记，尤其是威胁探测；在意识察觉之前触发恐惧。" } },
    { label: { en: "Dopamine Pathways", zh: "多巴胺通路" }, group: "Systems", note: { en: "Reward prediction circuits linking VTA to nucleus accumbens; drive motivation and habit.", zh: "连接腹侧被盖区与伏隔核的奖励预测回路；驱动动力与习惯形成。" } },
    { label: { en: "Prefrontal Cortex", zh: "前额叶皮层" }, group: "Systems", note: { en: "Executive control: planning, impulse inhibition, delayed gratification. Matures last (~age 25).", zh: "执行控制：规划、冲动抑制、延迟满足。是大脑中最晚成熟的区域（约25岁）。" } },
    { label: { en: "Basal Ganglia", zh: "基底神经节" }, group: "Systems", note: { en: "Automates habitual behaviour; the cue-routine-reward loop is stored here and resists erasure.", zh: "自动化习惯性行为；提示-常规-奖励回路储存于此，难以消除。" } },
    { label: { en: "Neuroplasticity", zh: "神经可塑性" }, group: "Systems", note: { en: "Brain-wide capacity to rewire synaptic connections in response to experience, practice, and environment.", zh: "大脑根据经验、练习和环境重连突触连接的整体能力。" } },
    { label: { en: "Default Mode Network", zh: "默认模式网络" }, group: "Systems", note: { en: "Active during rest and mind-wandering; central to self-referential thought and future simulation.", zh: "在休息和走神时活跃；是自我参照思维与未来模拟的核心网络。" } },
    { label: { en: "Cerebellum", zh: "小脑" }, group: "Systems", note: { en: "Coordinates movement and timing; increasingly implicated in cognitive and emotional processing.", zh: "协调运动与时序；越来越多的证据表明其参与认知和情绪加工。" } },
    { label: { en: "Anterior Cingulate Cortex", zh: "前扣带皮层" }, group: "Systems", note: { en: "Monitors conflict between competing responses; central to error detection and pain processing.", zh: "监测竞争性反应之间的冲突；是错误探测和疼痛加工的核心区域。" } },
    { label: { en: "Insula", zh: "岛叶" }, group: "Systems", note: { en: "Integrates bodily states with emotion (interoception); key to empathy and self-awareness.", zh: "整合身体状态与情绪（内感受）；是共情与自我意识的关键结构。" } }
  ],
  accent: "#4fd6c4",
};
export default sec;
