import type { Section } from "@/lib/types";
const sec: Section = {
  id: "human-simulator",
  num: 20,
  kicker: { en: "Factory 20 · You", zh: "工厂 20 · 你" },
  title: { en: "The Human Simulator", zh: "人生模拟器" },
  lead: { en: "Every person is a unique experiment run once — but the experiment is not random. Change where you were born, when you were born, into which family, and the probable arc of your life shifts dramatically. The factories are real, the forces are measurable, and yet the outcome remains irreducibly yours.", zh: "每一个人都是只运行一次的独特实验——但这个实验并非随机。改变你出生的地点、时间与家庭，你人生的可能轨迹便会发生深刻的改变。这些工厂是真实的，这些力量是可量化的，然而结果依然是不可化约的你自己。" },
  body: [
    { en: "This entire project has mapped the factories — genetic, prenatal, familial, cultural, geographic, historical, social, economic, neurological. What emerges from studying them together is a structural insight: the forces that shape a person do not determine a single outcome. They determine a band of likely outcomes. Your country of birth, your family's economic position, the era you arrived in — these set the width and the location of that band. They are the architecture. They do not write the life; they set the odds.", zh: "本项目的全部内容，是在绘制这些工厂的地图——基因、产前、家庭、文化、地理、历史、社会、经济、神经。将它们合并审视，一个结构性的洞见浮现出来：塑造一个人的力量，并不决定单一的结局。它们决定的是一个可能结局的区间。你的出生国、你家庭的经济地位、你所降生的时代——这些设定了那个区间的宽度与位置。它们是建筑结构。它们不书写人生；它们设置概率。" },
    { en: "Within that band, effort and luck compete and collaborate. The research on achievement consistently finds that neither talent nor effort alone explains extraordinary outcomes — timing, networks, random encounters, and the willingness to act on opportunity all carry independent weight. A child born into the top income quintile in a high-functioning state with universal healthcare and excellent schools begins with a much wider band of probable futures than a child born into a conflict zone with no educational infrastructure. Both children's futures remain open; the opening is dramatically different in size.", zh: "在那个区间之内，努力与运气相互竞争又彼此协作。关于成就的研究一致发现，无论是天赋还是努力单独都无法解释非凡的结局——时机、人脉、偶然的相遇，以及把握机遇的意愿，各自都具有独立的分量。一个出生在高收入五分位、拥有全民医疗和优质教育的高效能国家的孩子，与一个出生在冲突地区、没有教育基础设施的孩子相比，前者的可能未来区间要宽广得多。两个孩子的未来都是开放的；这个“开放”的幅度，却有着天壤之别。" },
    { en: "The simulator below lets you adjust five structural inputs and watch the probability landscape shift. It does not predict your life — it shows you the shape of the forces. The data behind each variable is drawn from real cross-national research: the Programme for International Student Assessment, the World Bank Intergenerational Mobility database, the Human Development Index, the Global Education Monitoring Report, and peer-reviewed economics of AI access. Treat the output as a probability lens, not a verdict.", zh: "下方的模拟器让你调节五个结构性输入，并观察概率图景的变化。它不预测你的人生——它展示力量的形态。每个变量背后的数据，来自真实的跨国研究：国际学生评估项目、世界银行代际流动数据库、人类发展指数、全球教育监测报告，以及经过同行评审的AI可及性经济学研究。请把输出结果视为概率镜头，而非判决。" },
    { en: "The deepest implication of the human factory is not fatalism but design. If we understand which forces narrow the band of human lives most severely, we can direct collective effort toward widening it — universal early education, healthcare that does not depend on postal code, AI tools that are genuinely accessible, institutions that convert luck into transferable opportunity. The factories are not destiny. They are infrastructure. And infrastructure is a choice.", zh: "人类制造厂最深刻的启示，不是宿命论，而是设计学。如果我们理解了哪些力量最严重地压缩了人类生命的可能区间，我们就能将集体努力导向拓宽它——普及早期教育、不依赖邮政编码的医疗保障、真正触手可及的AI工具、将运气转化为可传递机会的制度。这些工厂不是命运。它们是基础设施。而基础设施，是一种选择。" },
  ],
  cards: [
    { icon: "🌍", title: { en: "Country of Birth", zh: "出生国家" }, body: { en: "No single input carries more structural weight. Country determines baseline life expectancy, educational quality, healthcare access, rule of law, and the ceiling on intergenerational mobility. A child born in Norway and a child born in South Sudan face different arithmetic of probability — not because of who they are, but because of where they landed.", zh: "没有任何单一输入比这个具有更大的结构性分量。国家决定基准预期寿命、教育质量、医疗可及性、法治水平，以及代际流动的上限。一个生在挪威与一个生在南苏丹的孩子，面对的是不同的概率算术——不是因为他们是谁，而是因为他们降落在哪里。" } },
    { icon: "📅", title: { en: "Birth Year", zh: "出生年份" }, body: { en: "To be born in 1995 is to arrive when the internet is already a fact; to be born in 2015 is to arrive when smartphones are a given and AI is entering adolescence. The era assigns the technological context that will shape cognition, career options, and the texture of daily life. Birth year is the one input no one can choose — and it matters enormously.", zh: "生于1995年，意味着互联网已是既成事实；生于2015年，意味着智能手机是默认配置，AI正步入青春期。时代赋予了塑造认知、职业选项和日常生活质感的技术背景。出生年份是唯一没有人能够选择的输入——而它的影响极为深远。" } },
    { icon: "💰", title: { en: "Family Income", zh: "家庭收入" }, body: { en: "Family economic position shapes nutrition in the first thousand days, access to stimulating environments, neighbourhood safety, school quality, and the ability to take career risks. Research consistently shows that children from the top income quintile are four to five times more likely to reach the top quintile themselves than children from the bottom. The compounding begins before the child can walk.", zh: "家庭经济地位塑造了生命前一千天的营养、接触丰富环境的机会、社区安全、学校质量，以及承担职业风险的能力。研究持续表明，来自收入最高五分位的孩子，进入同一层级的可能性是来自最低五分位孩子的四至五倍。这种复利效应，在孩子学会走路之前便已开始。" } },
    { icon: "🎓", title: { en: "Education Access", zh: "教育机会" }, body: { en: "Years of schooling is the single most robust predictor of individual earnings across countries — but quality matters as much as quantity. A child completing twelve years of low-quality schooling may have lower functional literacy than a child completing eight years in a high-quality system. The simulator weights both years and estimated quality, because the credential is not the learning.", zh: "受教育年限是跨国范围内预测个人收入最稳健的单一指标——但质量与数量同等重要。一个完成十二年低质量教育的孩子，其功能性读写能力可能低于一个在高质量体系中完成八年教育的孩子。模拟器对年限与估计质量两者均加以权重，因为文凭不等于学习。" } },
  ],
  viz: "none",
  accent: "#f6cf86",
};
export default sec;
